package com.alfa.device_ctrl;

import org.junit.Test;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.zip.GZIPOutputStream;

import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

public final class RuntimeInstallerTest {
    @Test public void smokeCreatesAndExportsValidatedProotTempWorkspace() throws Exception { File temp=Files.createTempDirectory("alfa-proot-tmp-").toFile(); File staging=new File(temp,"staging"); assertTrue(staging.mkdirs()); File prootTmp=new File(staging,"proot_tmp"); assertTrue(prootTmp.mkdirs()); File canonical=prootTmp.getCanonicalFile(); assertTrue("PROOT_TMP_EXISTS",canonical.exists()); assertTrue("PROOT_TMP_DIRECTORY",canonical.isDirectory()); assertTrue("PROOT_TMP_WRITABLE",canonical.canWrite()); assertTrue("PROOT_TMP_EXECUTABLE",canonical.canExecute()); assertTrue("PROOT_TMP_INSIDE_STAGING",canonical.toPath().startsWith(staging.getCanonicalFile().toPath())); assertTrue("PROOT_TMP_DIR_EXPORT",canonical.getAbsolutePath().endsWith("/proot_tmp")); }
    @Test public void missingPackagedLoaderIsDeniedBeforeRuntimePublish() throws Exception { File temp=Files.createTempDirectory("alfa-loader-required-").toFile(); File engine=packagedEngine(temp); File loader=new File(engine.getParentFile(),"libproot-loader.so"); assertTrue("loader fixture must exist",loader.isFile()); assertTrue(loader.delete()); File archive=tarGz(temp,false); String engineHash=sha256(engine); RuntimeInstaller.Result result=installerWithFixtureArchive(temp,engine,archive).install("ubuntu",engine.toURI().toURL(),engineHash,registryBoundLocalUrl(RuntimeRegistry.get("ubuntu")),RuntimeRegistry.get("ubuntu").rootfsSha256(),true); assertFalse(result.success); assertTrue(result.message.contains("runtime-loader-invalid")||result.message.contains("ready-evidence-verification-failed")||result.message.contains("runtime-loader-missing")); assertFalse(new File(temp,"runtimes/ubuntu/READY.evidence").exists()); }
    @Test public void verifiedInstallCreatesEvidenceAndPublishesAtomically() throws Exception { File temp=Files.createTempDirectory("alfa-installer-test-").toFile(); File engine=packagedEngine(temp); File archive=tarGz(temp,false); String engineHash=sha256(engine); RuntimeInstaller.Result result=installerWithFixtureArchive(temp,engine,archive).install("ubuntu",engine.toURI().toURL(),engineHash,registryBoundLocalUrl(RuntimeRegistry.get("ubuntu")),RuntimeRegistry.get("ubuntu").rootfsSha256(),true); assertTrue(result.success); File runtime=new File(temp,"runtimes/ubuntu"); assertTrue(RuntimeEvidence.verify(new File(runtime,"READY.evidence"),"ubuntu",engine,new File(runtime,"rootfs"))); assertTrue(new File(runtime,"rootfs/bin/sh").isFile()); }
    @Test public void traversalIsDeniedAndPreviousReadyRuntimeSurvives() throws Exception { File temp=Files.createTempDirectory("alfa-installer-rollback-").toFile(); File engine=packagedEngine(temp); File valid=tarGz(temp,false); String engineHash=sha256(engine); RuntimeInstaller installer=installerWithFixtureArchive(temp,engine,valid); assertTrue(installer.install("ubuntu",engine.toURI().toURL(),engineHash,registryBoundLocalUrl(RuntimeRegistry.get("ubuntu")),RuntimeRegistry.get("ubuntu").rootfsSha256(),true).success); File runtime=new File(temp,"runtimes/ubuntu"); File evidence=new File(runtime,"READY.evidence"); File traversal=tarGz(temp,true); RuntimeInstaller.Result failed=installerWithFixtureArchive(temp,engine,traversal).install("ubuntu",engine.toURI().toURL(),engineHash,registryBoundLocalUrl(RuntimeRegistry.get("ubuntu")),RuntimeRegistry.get("ubuntu").rootfsSha256(),true); assertFalse(failed.success); assertTrue(RuntimeEvidence.verify(evidence,"ubuntu",engine,new File(runtime,"rootfs"))); assertFalse(new File(temp,"escape").exists()); }
    @Test public void checksumMismatchIsDenied() throws Exception { File temp=Files.createTempDirectory("alfa-installer-checksum-").toFile(); File engine=fakeEngine(temp); File archive=tarGz(temp,false); RuntimeInstaller.Result failed=new RuntimeInstaller(temp,null).install("ubuntu",engine.toURI().toURL(),"0000000000000000000000000000000000000000000000000000000000000000",registryBoundLocalUrl(RuntimeRegistry.get("ubuntu")),RuntimeRegistry.get("ubuntu").rootfsSha256(),true); assertFalse(failed.success); assertFalse(new File(temp,"runtimes/ubuntu/READY.evidence").exists()); }
    private static RuntimeInstaller installerWithFixtureArchive(File temp,File engine,File archive){return new RuntimeInstaller(temp,null,engine,engine.getParentFile(),(ignoredEngine,stagedRoot)->null,(url,dest,expected)->{assertTrue(RuntimeRegistry.get("ubuntu").rootfsUrl().equals(url.toString()));assertTrue(RuntimeRegistry.get("ubuntu").rootfsSha256().equalsIgnoreCase(expected));Files.copy(archive.toPath(),dest.toPath(),java.nio.file.StandardCopyOption.REPLACE_EXISTING);});}
    private static java.net.URL registryBoundLocalUrl(RuntimeProfile profile)throws Exception {return new java.net.URL(null,profile.rootfsUrl(),new java.net.URLStreamHandler(){protected java.net.URLConnection openConnection(java.net.URL ignored)throws IOException{return new java.net.URLConnection(ignored){public void connect(){}public java.io.InputStream getInputStream()throws IOException{return new java.io.FileInputStream(new File(ignored.getPath()));}};}});}
    private static File packagedEngine(File temp)throws Exception { File source=projectFixture("app/src/main/jniLibs/arm64-v8a/libproot.so"); File loaderSource=projectFixture("app/build/generated/jniLibs/arm64-v8a/libproot-loader.so"); assertTrue("trusted packaged engine fixture must exist",source.isFile()); assertTrue("canonical generated loader fixture must exist",loaderSource.isFile()); File nativeLibDir=new File(temp,"nativeLibs/arm64-v8a"); assertTrue(nativeLibDir.mkdirs()); File engine=new File(nativeLibDir,"libproot.so"); Files.copy(source.toPath(),engine.toPath()); assertTrue("fixture must be executable",engine.setExecutable(true,false)); assertTrue("fixture must be executable",engine.canExecute()); assertTrue("fixture hash must be trusted",RuntimeInstaller.TRUSTED_PROOT_ARM64_SHA256.equalsIgnoreCase(sha256(engine))); File loader=new File(nativeLibDir,"libproot-loader.so"); Files.copy(loaderSource.toPath(),loader.toPath()); assertTrue("loader fixture must be executable",loader.setExecutable(true,false)); assertTrue("loader fixture must be executable",loader.canExecute()); assertTrue("loader fixture hash must be trusted",RuntimeEvidence.isTrustedProotLoaderSha256(sha256(loader))); return engine; }
    private static File fakeEngine(File temp)throws Exception { File engine=new File(temp,"engine.sh"); Files.write(engine.toPath(),"#!/bin/sh\nprintf 'ALFA_RUNTIME_SMOKE_OK\\n0\\n/root\\n'\n".getBytes(StandardCharsets.UTF_8)); assertTrue(engine.setExecutable(true,false)); return engine; }
    private static File projectFixture(String relativePath){File working=new File(System.getProperty("user.dir"));File direct=new File(working,relativePath);if(direct.isFile())return direct;File parent=working.getParentFile();return parent==null?direct:new File(parent,relativePath);}
    private static File tarGz(File temp,boolean traversal)throws Exception {File archive=File.createTempFile("runtime-",".tar.gz",temp);try(OutputStream file=new FileOutputStream(archive);GZIPOutputStream gzip=new GZIPOutputStream(file)){entry(gzip,"bin/",new byte[0],'5');entry(gzip,"etc/",new byte[0],'5');entry(gzip,"usr/",new byte[0],'5');entry(gzip,"usr/bin/",new byte[0],'5');entry(gzip,traversal?"../escape":"bin/sh","#!/bin/sh\n".getBytes(StandardCharsets.UTF_8),'0');if(!traversal)entry(gzip,"usr/bin/env","#!/bin/sh\n".getBytes(StandardCharsets.UTF_8),'0');gzip.write(new byte[1024]);}return archive;}
    private static void entry(OutputStream out,String name,byte[]body,char type)throws IOException {byte[]header=new byte[512];put(header,0,100,name);put(header,100,8,"0000755");put(header,108,8,"0000000");put(header,116,8,"0000000");put(header,124,12,String.format("%011o",body.length));put(header,136,12,"00000000000");header[156]=(byte)type;put(header,257,6,"ustar");for(int i=148;i<156;i++)header[i]=' ';long sum=0;for(byte value:header)sum+=value&0xff;put(header,148,8,String.format("%06o",sum));out.write(header);out.write(body);int padding=(int)((512-(body.length%512))%512);if(padding>0)out.write(new byte[padding]);}
    private static void put(byte[]target,int offset,int width,String value){byte[]bytes=(value+"\0").getBytes(StandardCharsets.US_ASCII);System.arraycopy(bytes,0,target,offset,Math.min(value.length(),width));}
    private static String sha256(File file)throws Exception {MessageDigest digest=MessageDigest.getInstance("SHA-256");try(FileInputStream input=new FileInputStream(file)){byte[]buffer=new byte[65536];int count;while((count=input.read(buffer))>0)digest.update(buffer,0,count);}StringBuilder output=new StringBuilder();for(byte value: digest.digest())output.append(String.format("%02x",value&0xff));return output.toString();}
}
