plugins {
    id 'com.android.application'
}

android {
    namespace 'com.alfa.device_ctrl'
    compileSdk 35

    buildTypes {
        debug {
            debuggable true
        }
    }

    defaultConfig {
        applicationId 'com.alfa.device_ctrl'
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName '0.1.0'
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
    }
}

dependencies {
    implementation project(":terminal-view")
    implementation 'org.tukaani:xz:1.9'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test:runner:1.7.0'
    androidTestImplementation 'androidx.test.ext:junit:1.3.0'
}
