package com.alfa.device_ctrl;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.os.Build;
import android.provider.Settings;
import android.security.NetworkSecurityPolicy;
import android.view.Gravity;
import android.view.View;
import android.widget.Button;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;

import java.io.File;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/** Native Stitch v1 surfaces; runtime/network/storage execution stays inside Alfa boundaries. */
public final class AlfaStitchOperationalPanels {
    private static final int PAD = 12;
    private static final int RADIUS = 4;
    private AlfaStitchOperationalPanels() {}

    public static View build(Activity a, AlfaUiNavigation.Screen s, RuntimeSessionManager m, Runnable appearanceAction, Runnable refreshAction) {
        switch (s) {
            case NETWORK: return network(a);
            case SECURITY: return security(a);
            case STORAGE: return storage(a);
            case AUDIT: return audit(a);
            case PROJECT: return project(a);
            case SESSIONS: return sessions(a, m);
            case SPLIT: return split(a, m);
            case FLOATING: return floating(a);
            case APPEARANCE: return appearance(a, appearanceAction);
            case SETTINGS: return settings(a, refreshAction, appearanceAction);
            case DIAGNOSTICS: return diagnostics(a, m);
            default: return evidence(a, s.name(), "Canonical terminal/runtime surface handles this state.");
        }
    }

    private static View network(Activity a) { LinearLayout r=base(a,"NETWORK // EVIDENCE"); r.addView(AlfaNetworkPanel.build(a),new LinearLayout.LayoutParams(-1,0,1)); return r; }
    private static View security(Activity a) { LinearLayout r=base(a,"SECURITY // DIAGNOSTICS"),b=column(a); section(b,a,"APPLICATION","Package",a.getPackageName(),"SDK",String.valueOf(Build.VERSION.SDK_INT),"Debuggable",String.valueOf((a.getApplicationInfo().flags&android.content.pm.ApplicationInfo.FLAG_DEBUGGABLE)!=0)); section(b,a,"NETWORK SECURITY","Cleartext permitted",String.valueOf(NetworkSecurityPolicy.getInstance().isCleartextTrafficPermitted()),"VPN / firewall mutation","BLOCKED BY UI BOUNDARY","packet capture","NOT_CLAIMED"); section(b,a,"KERNEL / PRIVILEGE","ptrace","NOT_CLAIMED_FROM_APP_SANDBOX","seccomp","NOT_CLAIMED_FROM_APP_SANDBOX","privilege escalation","NOT_CLAIMED"); capability(b,a,"NO MOCK TELEMETRY","Security state is evidence-only; unsupported kernel state is never fabricated.",AlfaUiTheme.READY); return scroll(r,b); }
    private static View storage(Activity a) { LinearLayout r=base(a,"STORAGE // VFS POLICY"),b=column(a); section(b,a,"APP STORAGE","filesDir",a.getFilesDir().getAbsolutePath(),"externalFilesDir",externalFiles(a),"runtime vault",new File(a.getFilesDir(),"runtime-vault").getAbsolutePath()); section(b,a,"HOST STORAGE BOUNDARY","canonical host root",StitchV1ReferenceCatalog.CANONICAL_HOST_ROOT,"direct app access","NOT_ASSUMED","host visibility proof","SAF_OR_DEVICE_LAYER_REQUIRED"); LinearLayout c=card(a); c.addView(title(a,"DIRECTORY OVERRIDE // MOUNT ENFORCEMENT FLAGS"),full48(a)); c.addView(chip(a,"RW PERMISSIVE // DEV MODE",AlfaUiTheme.READY),full48(a)); c.addView(chip(a,"RO STRICT // IMMUTABLE",AlfaUiTheme.TEXT),full48(a)); c.addView(chip(a,"ISOLATED // MS_NODEV / MS_NOSUID",AlfaUiTheme.WARNING),full48(a)); c.addView(button(a,"BROWSE HOST DIRECTORY",AlfaUiTheme.CYAN,v->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT_TREE);i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION);a.startActivityForResult(i,0xA1F4);}),full48(a)); b.addView(c,wrap()); return scroll(r,b); }
    private static View audit(Activity a) { LinearLayout r=base(a,"AUDIT // PROVENANCE"),b=column(a); section(b,a,"STITCH V1 SOURCE","ZIP SHA-256",StitchV1ReferenceCatalog.ZIP_SHA256,"catalog states",String.valueOf(StitchV1ReferenceCatalog.size()),"mode","NATIVE_ANDROID_ADAPTERS"); section(b,a,"EXECUTION PROVENANCE","mock telemetry","NOT_USED","source artifact binding","LOCKED","reference HTML/JS","NOT_EXECUTED"); capability(b,a,"PROVENANCE BOUND","The raw Stitch ZIP is the implementation input and audit anchor.",AlfaUiTheme.READY); r.addView(b,new LinearLayout.LayoutParams(-1,0,1)); return r; }
    private static View project(Activity a) { LinearLayout r=base(a,"PROJECT EXPLORER"),b=column(a); section(b,a,"WORKSPACE","backend","ANDROID_APP_FILESYSTEM","workspace root",a.getFilesDir().getAbsolutePath(),"host browser","SAF_REQUIRED"); LinearLayout c=card(a); c.addView(title(a,"APP FILE TREE"),full48(a)); StringBuilder out=new StringBuilder(); tree(out,a.getFilesDir(),"",2,64); c.addView(mono(a,out.toString()),wrap()); b.addView(c,wrap()); r.addView(b,new LinearLayout.LayoutParams(-1,0,1)); return r; }

    private static View sessions(Activity a,RuntimeSessionManager m) {
        LinearLayout r=base(a,"SESSION MULTIPLEXER"),b=column(a); LinearLayout f=row(a,AlfaUiTheme.SURFACE_1); f.setWeightSum(4); filter(f,a,"ALL 15",AlfaUiTheme.READY); filter(f,a,"UBUNTU (5)",AlfaUiTheme.CYAN); filter(f,a,"KALI (5)",AlfaUiTheme.WARNING); filter(f,a,"ALPINE (5)",AlfaUiTheme.READY); b.addView(f,wrap());
        LinearLayout live=card(a); live.addView(title(a,"15 ACTIVE PTYS // CANONICAL SESSION"),full48(a)); String st=m==null?"MANAGER=UNAVAILABLE":m.isPromptReady()?"READY":m.isRunning()?"PTY_WAITING":"STOPPED"; live.addView(chip(a,"STATE="+st,AlfaUiTheme.statusColor(st)),full48(a)); String pid=m!=null&&m.currentSession()!=null?String.valueOf(m.currentSession().getPid()):"NONE"; live.addView(mono(a,"PID="+pid+"  //  MULTI-PTY BACKEND=NOT_EXPOSED_BY_CANONICAL_MANAGER"),wrap()); LinearLayout act=row(a,AlfaUiTheme.SURFACE_1); act.addView(button(a,"SYNC BROADCAST",AlfaUiTheme.CYAN,null),new LinearLayout.LayoutParams(0,dp(a,48),1)); act.addView(button(a,"+ SPAWN PTY",AlfaUiTheme.READY,v->{if(m!=null)m.start(80,24,0,0);}),new LinearLayout.LayoutParams(0,dp(a,48),1)); act.addView(button(a,"STOP SESSION",AlfaUiTheme.ERROR,v->{if(m!=null)m.stop();}),new LinearLayout.LayoutParams(0,dp(a,48),1)); live.addView(act,wrap()); b.addView(live,wrap());
        LinearLayout lanes=card(a); lanes.addView(title(a,"REFERENCE SESSION LANES // 15 TOTAL"),full48(a)); String[] rs={"UBUNTU 24.04 LTS","KALI NETHUNTER ROOTLESS","ALPINE LINUX 3.24.1"}; for(String x:rs) for(int i=1;i<=5;i++){LinearLayout q=row(a,AlfaUiTheme.SURFACE_1);q.addView(text(a,x+" // #"+String.format("%02d",i)+"  // PTS="+(i-1),AlfaUiTheme.TEXT,10,true),new LinearLayout.LayoutParams(0,dp(a,48),1)); Button sw=button(a,"SWITCH ↔",AlfaUiTheme.TEXT_MUTED,null);sw.setEnabled(false);sw.setContentDescription("Switch session belum tersedia di canonical manager");q.addView(sw,new LinearLayout.LayoutParams(dp(a,104),dp(a,48)));lanes.addView(q,wrap());} lanes.addView(chip(a,"REFERENCE_MULTIPLE_SESSIONS=CATALOG_STATE_WITHOUT_FABRICATED_PTYS",AlfaUiTheme.WARNING),full48(a)); b.addView(lanes,wrap()); return scroll(r,b);
    }
    private static void filter(LinearLayout p,Activity a,String s,int c){p.addView(button(a,s,c,null),new LinearLayout.LayoutParams(0,dp(a,48),1));}

    private static View split(Activity a,RuntimeSessionManager m){ LinearLayout r=base(a,"DUAL TTY // RUNTIME CONTROL"),b=column(a),c=card(a); c.addView(chip(a,"SYNC: DUAL BROADCAST",AlfaUiTheme.READY),full48(a)); c.addView(chip(a,"SPLIT: VERT / HORIZ",AlfaUiTheme.CYAN),full48(a)); c.addView(chip(a,"SECOND PTY=NOT_EXPOSED_BY_CANONICAL_MANAGER",AlfaUiTheme.WARNING),full48(a)); b.addView(c,wrap()); LinearLayout panes=row(a,AlfaUiTheme.CANVAS);panes.setWeightSum(2);panes.addView(pane(a,"PANE 1 // CANONICAL PTY",sessionState(m),AlfaUiTheme.TEXT),new LinearLayout.LayoutParams(0,-1,1));panes.addView(pane(a,"PANE 2 // CAPABILITY GATE","ATTACHMENT=NOT_AVAILABLE\nNo second PTY is fabricated.",AlfaUiTheme.TEXT_MUTED),new LinearLayout.LayoutParams(0,-1,1));b.addView(panes,new LinearLayout.LayoutParams(-1,0,1));r.addView(b,new LinearLayout.LayoutParams(-1,0,1));return r; }
    private static View floating(Activity a){boolean allowed=Build.VERSION.SDK_INT<23||Settings.canDrawOverlays(a);LinearLayout r=base(a,"FLOATING TERMINAL // WINDOW OVERLAY"),b=column(a);section(b,a,"OVERLAY CAPABILITY","overlay permission",String.valueOf(allowed),"window mode",allowed?"CAPABLE":"BLOCKED","interactive overlay","NOT_STARTED_BY_THIS_PANEL");LinearLayout c=card(a);c.addView(title(a,"PENGATURAN // IN-WINDOW SETTINGS"),full48(a));c.addView(chip(a,"OPACITY 95% // VISUAL CONTRACT",AlfaUiTheme.CYAN),full48(a));c.addView(chip(a,"FONT 14sp // TERMINAL PTY",AlfaUiTheme.TEXT),full48(a));c.addView(chip(a,"ALWAYS ON TOP // ANDROID OVERLAY",AlfaUiTheme.TEXT),full48(a));c.addView(chip(a,"RESIZABLE // MIN 280dp × 200dp",AlfaUiTheme.READY),full48(a));b.addView(c,wrap());b.addView(button(a,allowed?"OVERLAY ALREADY ALLOWED":"OPEN OVERLAY PERMISSION",allowed?AlfaUiTheme.READY:AlfaUiTheme.CYAN,v->{if(!allowed)a.startActivity(new Intent(Settings.ACTION_MANAGE_OVERLAY_PERMISSION,Uri.parse("package:"+a.getPackageName())));}),full48(a));b.addView(chip(a,"NO_FAKE_FLOATING_WINDOW",AlfaUiTheme.WARNING),full48(a));r.addView(b,new LinearLayout.LayoutParams(-1,0,1));return r; }

    private static View appearance(Activity a,Runnable openExisting){LinearLayout r=base(a,"ALFA CONTROL CENTER // PENGATURAN KONSOL"),b=column(a);LinearLayout t=card(a);t.addView(title(a,"01 // APPEARANCE // TEMA & TAMPILAN"),full48(a));t.addView(preset(a,"Terminal Obsidian","Active // Default",AlfaUiTheme.READY),wrap());t.addView(preset(a,"Obsidian Cyan Sub-zero","Sub-zero matrix",AlfaUiTheme.CYAN),wrap());t.addView(preset(a,"Classic Amber VT220","VT220 phosphor",AlfaUiTheme.WARNING),wrap());t.addView(preset(a,"High Contrast","Pure 21:1 Delta",AlfaUiTheme.TEXT),wrap());b.addView(t,wrap());LinearLayout ty=card(a);ty.addView(title(a,"02 // TYPOGRAPHY // TIPOGRAFI SISTEM & PTY"),full48(a));ty.addView(step(a,"TERM FONT SIZE","13sp"),wrap());ty.addView(step(a,"PTY LINE HEIGHT","1.25x"),wrap());ty.addView(chip(a,"FONT STACK // Geist Sans (UI) / JetBrains Mono (PTY)",AlfaUiTheme.TEXT_MUTED),full48(a));b.addView(ty,wrap());LinearLayout ts=card(a);ts.addView(title(a,"03 // TERMINAL SETTINGS"),full48(a));ts.addView(chip(a,"CURSOR STYLE // BLOCK / UNDERLINE / BAR",AlfaUiTheme.CYAN),full48(a));ts.addView(chip(a,"CURSOR BLINK // ENABLED",AlfaUiTheme.READY),full48(a));ts.addView(chip(a,"SCROLLBACK BUFFER // 10,000 LINES",AlfaUiTheme.TEXT),full48(a));b.addView(ts,wrap());LinearLayout g=card(a);g.addView(title(a,"04 // FLOATING WINDOW GEOMETRY"),full48(a));g.addView(chip(a,"COMPACT / STANDARD / EXPANDED / CUSTOM",AlfaUiTheme.CYAN),full48(a));g.addView(chip(a,"VIEWPORT 92% × 55% // OVERLAY ALPHA 90%",AlfaUiTheme.READY),full48(a));b.addView(g,wrap());LinearLayout im=card(a);im.addView(title(a,"05 // INTERACTION & PTY ACCESSORY"),full48(a));im.addView(chip(a,"ACCESSORY BAR POSITION // ABOVE IME",AlfaUiTheme.CYAN),full48(a));im.addView(chip(a,"MULTILINE PASTE CONFIRMATION // ENABLED",AlfaUiTheme.READY),full48(a));b.addView(im,wrap());LinearLayout d=card(a);d.addView(title(a,"06 // SYSTEM INFORMATION & DIAGNOSTICS"),full48(a));d.addView(mono(a,"Application Build // Alfa Device Ctrl\nKernel substrate // Shizuku / Rish boundary\nDump Syslogs / Flush PTY Cache // existing diagnostic actions"),wrap());b.addView(d,wrap());b.addView(button(a,"OPEN TERMINAL APPEARANCE // APPLY REAL SETTINGS",AlfaUiTheme.CYAN,v->openExisting.run()),full48(a));return scroll(r,b); }
    private static View settings(Activity a,Runnable refresh,Runnable appearance){return appearance(a,appearance);}
    private static View diagnostics(Activity a,RuntimeSessionManager m){LinearLayout r=base(a,"DIAGNOSTIC ENGINE"),b=column(a);section(b,a,"RUNTIME","session",sessionState(m),"registry count",String.valueOf(RuntimeRegistry.all().size()),"Stitch states",String.valueOf(StitchV1ReferenceCatalog.size()));section(b,a,"NETWORK","panel","LIVE_READ_ONLY","DNS / routes / interface","EVIDENCE-BACKED","privileged mutation","BLOCKED");section(b,a,"SECURITY","sandbox claims","NOT_CLAIMED_FROM_APP_SANDBOX","mock telemetry","NOT_USED","unsupported kernel state","BLOCKED");capability(b,a,"DIAGNOSTIC ENGINE","Network, runtime, security and storage surfaces report boundaries instead of inventing capabilities.",AlfaUiTheme.READY);r.addView(b,new LinearLayout.LayoutParams(-1,0,1));return r;}
    private static View evidence(Activity a,String t,String s){LinearLayout r=base(a,t);r.addView(mono(a,s),new LinearLayout.LayoutParams(-1,0,1));return r;}

    private static LinearLayout base(Activity a,String s){LinearLayout r=column(a);r.setPadding(dp(a,8),dp(a,4),dp(a,8),0);TextView h=text(a,s,AlfaUiTheme.CYAN,13,true);h.setTypeface(Typeface.MONOSPACE,Typeface.BOLD);r.addView(h,new LinearLayout.LayoutParams(-1,dp(a,56)));return r;}
    private static LinearLayout column(Context c){LinearLayout l=new LinearLayout(c);l.setOrientation(LinearLayout.VERTICAL);l.setBackgroundColor(AlfaUiTheme.CANVAS);return l;}
    private static LinearLayout row(Context c,int bg){LinearLayout l=new LinearLayout(c);l.setOrientation(LinearLayout.HORIZONTAL);l.setGravity(Gravity.CENTER_VERTICAL);l.setBackgroundColor(bg);return l;}
    private static LinearLayout card(Context c){LinearLayout l=column(c);l.setPadding(dp(c,6),dp(c,6),dp(c,6),dp(c,6));GradientDrawable g=new GradientDrawable();g.setColor(AlfaUiTheme.SURFACE_1);g.setCornerRadius(dp(c,RADIUS));g.setStroke(Math.max(1,dp(c,1)),AlfaUiTheme.BORDER);l.setBackground(g);return l;}
    private static TextView title(Context c,String s){TextView v=text(c,s,AlfaUiTheme.TEXT,11,true);v.setTypeface(Typeface.MONOSPACE,Typeface.BOLD);return v;}
    private static TextView mono(Context c,String s){return text(c,s,AlfaUiTheme.TEXT,11,true);}
    private static TextView text(Context c,String s,int color,int size,boolean mono){TextView v=new TextView(c);v.setText(s);v.setTextColor(color);v.setTextSize(size);if(mono)v.setTypeface(Typeface.MONOSPACE);v.setGravity(Gravity.CENTER_VERTICAL);return v;}
    private static Button button(Context c,String s,int color,View.OnClickListener l){Button b=new Button(c);b.setText(s);b.setTextColor(color);b.setTextSize(10);b.setAllCaps(false);b.setMinHeight(dp(c,AlfaUiTheme.TOUCH_TARGET_DP));b.setMinWidth(dp(c,AlfaUiTheme.TOUCH_TARGET_DP));b.setBackground(controlBg(c,color));if(l!=null)b.setOnClickListener(l);return b;}
    private static TextView chip(Context c,String s,int color){TextView v=text(c,s,color,10,true);v.setPadding(dp(c,10),0,dp(c,10),0);v.setBackground(controlBg(c,color));return v;}
    private static View preset(Activity a,String n,String st,int c){LinearLayout r=row(a,AlfaUiTheme.SURFACE_2);r.addView(text(a,"■  "+n,AlfaUiTheme.TEXT,10,true),new LinearLayout.LayoutParams(0,dp(a,48),2));r.addView(text(a,st,c,9,true),new LinearLayout.LayoutParams(0,dp(a,48),1));return r;}
    private static View step(Activity a,String n,String v){LinearLayout r=row(a,AlfaUiTheme.SURFACE_2);r.addView(text(a,n,AlfaUiTheme.TEXT_MUTED,10,true),new LinearLayout.LayoutParams(0,dp(a,48),1));r.addView(button(a,"−",AlfaUiTheme.TEXT,null),new LinearLayout.LayoutParams(dp(a,48),dp(a,48)));r.addView(text(a,v,AlfaUiTheme.READY,11,true),new LinearLayout.LayoutParams(dp(a,60),dp(a,48)));r.addView(button(a,"+",AlfaUiTheme.TEXT,null),new LinearLayout.LayoutParams(dp(a,48),dp(a,48)));return r;}
    private static void section(LinearLayout b,Activity a,String t,String...p){LinearLayout c=card(a);c.addView(title(a,t),full48(a));for(int i=0;i+1<p.length;i+=2){LinearLayout q=row(a,AlfaUiTheme.SURFACE_1);q.addView(text(a,p[i],AlfaUiTheme.TEXT_MUTED,10,true),new LinearLayout.LayoutParams(0,dp(a,48),1));q.addView(text(a,p[i+1],AlfaUiTheme.TEXT,10,true),new LinearLayout.LayoutParams(0,dp(a,48),2));c.addView(q,wrap());}b.addView(c,wrap());}
    private static void capability(LinearLayout b,Activity a,String t,String d,int c){LinearLayout x=card(a);x.addView(chip(a,t,c),full48(a));x.addView(text(a,d,AlfaUiTheme.TEXT_MUTED,10,false),wrap());b.addView(x,wrap());}
    private static View pane(Activity a,String t,String s,int c){LinearLayout x=card(a);x.addView(chip(a,t,c),full48(a));x.addView(mono(a,s),new LinearLayout.LayoutParams(-1,0,1));return x;}
    private static View scroll(LinearLayout r,LinearLayout b){ScrollView s=new ScrollView(r.getContext());s.addView(b);r.addView(s,new LinearLayout.LayoutParams(-1,0,1));return r;}
    private static LinearLayout.LayoutParams wrap(){return new LinearLayout.LayoutParams(-1,-2);}
    private static LinearLayout.LayoutParams full48(Context c){return new LinearLayout.LayoutParams(-1,dp(c,AlfaUiTheme.TOUCH_TARGET_DP));}
    private static GradientDrawable controlBg(Context c,int color){GradientDrawable g=new GradientDrawable();g.setColor(AlfaUiTheme.SURFACE_2);g.setCornerRadius(dp(c,4));g.setStroke(Math.max(1,dp(c,1)),color);return g;}
    private static int dp(Context c,int value){return (int)(value*c.getResources().getDisplayMetrics().density+0.5f);}
    private static String externalFiles(Activity a){File f=a.getExternalFilesDir(null);return f==null?"UNAVAILABLE":f.getAbsolutePath();}
    private static String sessionState(RuntimeSessionManager m){if(m==null)return "MANAGER=UNAVAILABLE";if(!m.isRunning())return "STOPPED";return m.isPromptReady()?"READY":"PTY_WAITING_FOR_PROMPT";}
    private static void tree(StringBuilder out,File dir,String prefix,int depth,int max){if(depth<0||max<=0)return;File[] fs=dir.listFiles();if(fs==null){out.append(prefix).append("<unreadable>\n");return;}List<File> l=new ArrayList<>();Collections.addAll(l,fs);Collections.sort(l,(x,y)->x.getName().compareToIgnoreCase(y.getName()));int n=0;for(File f:l){if(n++>=max){out.append(prefix).append("… truncated\n");break;}out.append(prefix).append(f.getName()).append(f.isDirectory()?"/":"").append('\n');if(f.isDirectory())tree(out,f,prefix+"  ",depth-1,max);}}
}
