package com.alfa.device_ctrl;

import android.app.Activity;
import android.graphics.Typeface;
import android.os.Build;
import android.view.Gravity;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.LinearLayout;
import android.widget.TextView;

/** Final-shell navigation bindings for evidence-backed Stitch operational states. */
public final class AlfaFinalUiHooks {
    private static final int TAG_ID = 0xA1FA002;
    private AlfaFinalUiHooks() { }
    public static void apply(Activity activity){View root=activity.findViewById(android.R.id.content);if(!(root instanceof ViewGroup)||root.getTag(TAG_ID)!=null)return;addStitchLauncher(activity,(ViewGroup)root);root.setTag(TAG_ID,Boolean.TRUE);}
    private static void addStitchLauncher(Activity activity,ViewGroup content){Button launcher=new Button(activity);launcher.setText("STITCH");launcher.setTextColor(AlfaUiTheme.CYAN);launcher.setTypeface(Typeface.MONOSPACE,Typeface.BOLD);launcher.setMinWidth(dp(activity,72));launcher.setMinHeight(dp(activity,48));launcher.setContentDescription("Buka seluruh panel operasional Stitch v1");launcher.setOnClickListener(v->showDomainMenu(activity,content));if(content instanceof android.widget.FrameLayout){android.widget.FrameLayout.LayoutParams params=new android.widget.FrameLayout.LayoutParams(dp(activity,82),dp(activity,48),Gravity.TOP|Gravity.END);params.setMargins(0,dp(activity,8),dp(activity,8),0);content.addView(launcher,params);}else content.addView(launcher,new ViewGroup.LayoutParams(dp(activity,82),dp(activity,48)));}
    private static void showDomainMenu(Activity activity,ViewGroup content){LinearLayout menu=new LinearLayout(activity);menu.setOrientation(LinearLayout.VERTICAL);menu.setBackgroundColor(AlfaUiTheme.CANVAS);menu.setPadding(dp(activity,12),dp(activity,8),dp(activity,12),dp(activity,12));TextView title=text(activity,"STITCH V1 • OPERATIONAL STATES",AlfaUiTheme.CYAN,14,true);menu.addView(title,new LinearLayout.LayoutParams(-1,dp(activity,52)));Button catalog=new Button(activity);catalog.setText("159 STATE CATALOG");catalog.setTextColor(AlfaUiTheme.READY);catalog.setMinHeight(dp(activity,48));catalog.setContentDescription("Open all 159 Stitch states");RuntimeSessionManager manager=findSessionManager(activity);catalog.setOnClickListener(v->showOverlay(activity,content,StitchV1StatePanel.build(activity,manager,screen->showPanel(activity,content,screen))));menu.addView(catalog,new LinearLayout.LayoutParams(-1,dp(activity,48)));String[] names={"NETWORK","SECURITY","STORAGE","AUDIT","PROJECT","SESSIONS","SPLIT","FLOATING","APPEARANCE","SETTINGS","DIAGNOSTICS"};AlfaUiNavigation.Screen[] screens={AlfaUiNavigation.Screen.NETWORK,AlfaUiNavigation.Screen.SECURITY,AlfaUiNavigation.Screen.STORAGE,AlfaUiNavigation.Screen.AUDIT,AlfaUiNavigation.Screen.PROJECT,AlfaUiNavigation.Screen.SESSIONS,AlfaUiNavigation.Screen.SPLIT,AlfaUiNavigation.Screen.FLOATING,AlfaUiNavigation.Screen.APPEARANCE,AlfaUiNavigation.Screen.SETTINGS,AlfaUiNavigation.Screen.DIAGNOSTICS};for(int i=0;i<names.length;i++){final AlfaUiNavigation.Screen screen=screens[i];Button button=new Button(activity);button.setText(names[i]);button.setTextColor(AlfaUiTheme.TEXT);button.setMinHeight(dp(activity,48));button.setOnClickListener(v->showPanel(activity,content,screen));menu.addView(button,new LinearLayout.LayoutParams(-1,dp(activity,48)));}showOverlay(activity,content,menu);}
    private static void showPanel(Activity activity,ViewGroup content,AlfaUiNavigation.Screen screen){View panel=AlfaStitchOperationalPanels.build(activity,screen,findSessionManager(activity),()->showPanel(activity,content,AlfaUiNavigation.Screen.APPEARANCE),()->{});showOverlay(activity,content,panel);}
    private static RuntimeSessionManager findSessionManager(Activity activity){try{java.lang.reflect.Field field=StitchOperationalActivity.class.getDeclaredField("sessionManager");field.setAccessible(true);return(RuntimeSessionManager)field.get(activity);}catch(Exception ignored){return null;}}
    private static void showOverlay(Activity activity,ViewGroup content,View panel){android.widget.FrameLayout overlay=new android.widget.FrameLayout(activity);overlay.setBackgroundColor(AlfaUiTheme.CANVAS);final android.window.OnBackInvokedCallback[] callback=new android.window.OnBackInvokedCallback[1];Runnable close=()->{content.removeView(overlay);if(Build.VERSION.SDK_INT>=33&&callback[0]!=null)activity.getOnBackInvokedDispatcher().unregisterOnBackInvokedCallback(callback[0]);};overlay.addView(panel,new android.widget.FrameLayout.LayoutParams(-1,-1));Button closeButton=new Button(activity);closeButton.setText("BACK");closeButton.setTextColor(AlfaUiTheme.CYAN);closeButton.setMinHeight(dp(activity,48));closeButton.setOnClickListener(v->close.run());android.widget.FrameLayout.LayoutParams closeParams=new android.widget.FrameLayout.LayoutParams(dp(activity,76),dp(activity,48),Gravity.TOP|Gravity.END);closeParams.setMargins(0,dp(activity,8),dp(activity,8),0);overlay.addView(closeButton,closeParams);content.addView(overlay,new android.widget.FrameLayout.LayoutParams(-1,-1));if(Build.VERSION.SDK_INT>=33){callback[0]=close::run;activity.getOnBackInvokedDispatcher().registerOnBackInvokedCallback(android.window.OnBackInvokedDispatcher.PRIORITY_OVERLAY,callback[0]);}}
    private static TextView text(Activity activity,String value,int color,int size,boolean mono){TextView t=new TextView(activity);t.setText(value);t.setTextColor(color);t.setTextSize(size);if(mono)t.setTypeface(Typeface.MONOSPACE);return t;}private static int dp(Activity activity,int value){return Math.round(value*activity.getResources().getDisplayMetrics().density);}
}
