package com.alfa.device_ctrl;
import android.app.Activity;import android.graphics.Color;import android.os.Bundle;import android.view.Gravity;import android.widget.LinearLayout;import android.widget.TextView;import java.io.File;
/** Security/policy surface whose status is derived from the real interactive-session contract. */
public final class PolicyEvidenceActivity extends Activity{
 private static final int BG=Color.rgb(19,19,21),PRIMARY=Color.rgb(171,199,255),MUTED=Color.rgb(193,198,213);
 @Override protected void onCreate(Bundle state){super.onCreate(state);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);root.setPadding(dp(14),dp(14),dp(14),dp(14));TextView title=text("SECURITY / INTERACTIVE POLICY",PRIMARY,16,true);root.addView(title,new LinearLayout.LayoutParams(-1,dp(52)));String runtimeId=AlfaSettingsStore.get(this).getRuntimeId(RuntimeSelection.DEFAULT_RUNTIME_ID);StringBuilder r=new StringBuilder();r.append("POLICY_ID=").append(InteractiveSessionContract.POLICY_ID).append('\n');r.append("POLICY_VERSION=").append(InteractiveSessionContract.POLICY_VERSION).append('\n');r.append("POLICY_SCOPE=").append(InteractiveSessionContract.POLICY_SCOPE).append('\n');r.append("RUNTIME_ID=").append(runtimeId).append('\n');r.append("ANDROID_ROOT=NOT_GRANTED_BY_APP\nOTHER_APP_DATA=NOT_GRANTED_BY_APP\n");RuntimeProfile p=RuntimeSelection.profile(runtimeId);if(p==null)r.append("CONTRACT_STATUS=BLOCKED\nREASON=unsupported-runtime-id");else{File files=getFilesDir(),vault=new File(files,"runtime-vault"),runtime=new File(new File(vault,"runtimes"),runtimeId),ready=new File(runtime,"READY.evidence"),launch=new File(vault,"gate7-launch.properties"),engine=new File(getApplicationInfo().nativeLibraryDir,"libproot.so"),rootfs=new File(runtime,"rootfs"),cwd=new File(files,"session-cwd");r.append("GATE7_LAUNCH=").append(Gate6LaunchContract.verify(launch,runtimeId)?"PASS":"BLOCKED").append('\n');r.append("RUNTIME_READY_EVIDENCE=").append(RuntimeEvidence.verify(ready,runtimeId,engine,rootfs)?"PASS":"BLOCKED").append('\n');try{if(!cwd.exists()&&!cwd.mkdirs())throw new IllegalStateException("session-cwd-unavailable");InteractiveSessionContract c=new InteractiveSessionContract("policy-inspection","policy-inspection","policy-inspection",runtimeId,ready,engine,rootfs,cwd,new String[]{"HOME=/root","TERM=xterm-256color","PS1=alfa:"+runtimeId+":\\w\\$ ","PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin","PROOT_TMP_DIR="+new File(runtime,"proot_tmp").getAbsolutePath()});r.append("CONTRACT_STATUS=").append(c.isAuthorizedForInteractiveRuntime()?"AUTHORIZED":"BLOCKED").append('\n');r.append("PROOT_LOADER_POLICY=REQUIRED_AND_RUNTIME_BOUND\nRUNTIME_ROOT=").append(rootfs.getCanonicalPath()).append('\nHOST_CWD=").append(cwd.getCanonicalPath());}catch(Exception e){r.append("CONTRACT_STATUS=BLOCKED\nREASON=").append(e.getClass().getSimpleName()).append(':').append(e.getMessage());}}
 TextView body=text(r.toString(),MUTED,11,false);body.setTypeface(android.graphics.Typeface.MONOSPACE);body.setGravity(Gravity.TOP|Gravity.START);root.addView(body,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);}
 private TextView text(String v,int c,int s,boolean b){TextView t=new TextView(this);t.setText(v);t.setTextColor(c);t.setTextSize(s);if(b)t.setTypeface(android.graphics.Typeface.MONOSPACE,android.graphics.Typeface.BOLD);return t;}private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}
}
