package com.alfa.device_ctrl;

import android.app.Activity;import android.content.Intent;import android.net.Uri;import android.os.Bundle;import android.view.Gravity;import android.view.View;import android.widget.Button;import android.widget.EditText;import android.widget.LinearLayout;import android.widget.TextView;import java.util.ArrayDeque;import java.util.Deque;import java.util.List;

/** Real SAF-backed project explorer. It never resolves a guessed filesystem path. */
public final class ProjectExplorerActivity extends Activity {
 private static final int PICK_TREE=4101; private static final int BG=android.graphics.Color.rgb(19,19,21),PRIMARY=android.graphics.Color.rgb(171,199,255),MUTED=android.graphics.Color.rgb(193,198,213);
 private final Deque<Uri> parents=new ArrayDeque<>(); private SafHostStorageProvider provider; private Uri current; private LinearLayout list; private TextView state;
 @Override protected void onCreate(Bundle s){super.onCreate(s);provider=new SafHostStorageProvider(this);buildUi();current=provider.treeUri();if(current==null||!provider.hasPersistedAccess())showState("HOST_STORAGE=NOT_CONFIGURED\nPilih folder canonical Alfa melalui SAF.");else load(current);}
 private void buildUi(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);root.setPadding(dp(10),dp(10),dp(10),dp(10));LinearLayout header=new LinearLayout(this);header.setGravity(Gravity.CENTER_VERTICAL);TextView title=text("PROJECT EXPLORER",PRIMARY,15,true);header.addView(title,new LinearLayout.LayoutParams(0,dp(48),1));Button choose=button("HOST",PRIMARY,v->startActivityForResult(provider.createTreePickerIntent(),PICK_TREE));choose.setContentDescription("Pilih folder host melalui SAF");header.addView(choose,new LinearLayout.LayoutParams(dp(72),dp(48)));root.addView(header);state=text("",MUTED,10,false);state.setTypeface(android.graphics.Typeface.MONOSPACE);root.addView(state,new LinearLayout.LayoutParams(-1,dp(54)));LinearLayout actions=new LinearLayout(this);Button up=button("UP",MUTED,v->goUp()),mkdir=button("DIR +",MUTED,v->create(true)),file=button("FILE +",MUTED,v->create(false)),refresh=button("REFRESH",MUTED,v->{if(current!=null)load(current);});actions.addView(up,weight());actions.addView(mkdir,weight());actions.addView(file,weight());actions.addView(refresh,weight());root.addView(actions,new LinearLayout.LayoutParams(-1,dp(52)));list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);root.addView(list,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);}
 private void load(Uri uri){current=uri;new Thread(()->{try{List<SafHostStorageProvider.Entry> entries=provider.list(uri);runOnUiThread(()->render(uri,entries));}catch(Exception e){runOnUiThread(()->showState("HOST_STORAGE=ERROR\n"+e.getClass().getSimpleName()+":"+e.getMessage()));}},"alfa-saf-list").start();}
 private void render(Uri uri,List<SafHostStorageProvider.Entry> entries){list.removeAllViews();state.setText("HOST_STORAGE=SAF\n"+uri+"\nENTRIES="+entries.size());for(SafHostStorageProvider.Entry entry:entries){LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);TextView name=text((entry.isDirectory()?"DIR  ":"FILE ")+entry.name,PRIMARY,11,true);row.addView(name,new LinearLayout.LayoutParams(0,dp(50),1));if(entry.isDirectory()){Button open=button("OPEN",PRIMARY,v->{parents.push(current);load(entry.uri);});open.setContentDescription("Buka folder "+entry.name);row.addView(open,new LinearLayout.LayoutParams(dp(76),dp(48)));}else{Button view=button("VIEW",MUTED,v->preview(entry));view.setContentDescription("Baca file "+entry.name);row.addView(view,new LinearLayout.LayoutParams(dp(76),dp(48)));}Button del=button("×",android.graphics.Color.rgb(255,180,171),v->confirmDelete(entry));del.setContentDescription("Hapus "+entry.name);row.addView(del,new LinearLayout.LayoutParams(dp(48),dp(48)));list.addView(row);}}
 private void preview(SafHostStorageProvider.Entry e){new Thread(()->{try{String c=provider.readUtf8(e.uri);runOnUiThread(()->new android.app.AlertDialog.Builder(this).setTitle(e.name).setMessage(c).setPositiveButton("OK",null).show());}catch(Exception x){runOnUiThread(()->showState("READ=BLOCKED\n"+x.getMessage()));}},"alfa-saf-read").start();}
 private void create(boolean dir){if(current==null){showState("CREATE=BLOCKED\nPilih folder host terlebih dahulu.");return;}EditText input=new EditText(this);input.setHint(dir?"Nama folder":"Nama file.txt");new android.app.AlertDialog.Builder(this).setTitle(dir?"Buat folder":"Buat file").setView(input).setNegativeButton("Batal",null).setPositiveButton("Buat",(d,w)->new Thread(()->{try{if(dir)provider.createDirectory(current,input.getText().toString());else provider.createTextFile(current,input.getText().toString());runOnUiThread(()->load(current));}catch(Exception e){runOnUiThread(()->showState("CREATE=BLOCKED\n"+e.getMessage()));}},"alfa-saf-create").start()).show();}
 private void confirmDelete(SafHostStorageProvider.Entry e){new android.app.AlertDialog.Builder(this).setTitle("Hapus "+e.name+"?").setMessage("Operasi dikirim ke DocumentsProvider melalui content:// URI.").setNegativeButton("Batal",null).setPositiveButton("Hapus",(d,w)->new Thread(()->{try{boolean ok=provider.delete(e.uri);runOnUiThread(()->{showState("DELETE="+(ok?"PASS":"BLOCKED"));load(current);});}catch(Exception x){runOnUiThread(()->showState("DELETE=BLOCKED\n"+x.getMessage()));}},"alfa-saf-delete").start()).show();}
 private void goUp(){if(!parents.isEmpty())load(parents.pop());else showState(current==null?"HOST_STORAGE=NOT_CONFIGURED":"PROJECT_ROOT=ACTIVE");}
 @Override protected void onActivityResult(int r,int result,Intent data){super.onActivityResult(r,result,data);if(r==PICK_TREE&&result==RESULT_OK&&data!=null&&data.getData()!=null){Uri selected=data.getData();if(provider.persistTreeUri(selected)){parents.clear();load(selected);}else showState("HOST_STORAGE=BLOCKED\nSAF persistable read/write grant was not accepted.");}}
 private void showState(String v){if(state!=null)state.setText(v);}private TextView text(String v,int c,int s,boolean b){TextView t=new TextView(this);t.setText(v);t.setTextColor(c);t.setTextSize(s);if(b)t.setTypeface(android.graphics.Typeface.MONOSPACE,android.graphics.Typeface.BOLD);return t;}private Button button(String v,int c,View.OnClickListener l){Button b=new Button(this);b.setText(v);b.setTextColor(c);b.setTextSize(10);b.setAllCaps(false);b.setMinHeight(dp(48));b.setOnClickListener(l);return b;}private LinearLayout.LayoutParams weight(){return new LinearLayout.LayoutParams(0,dp(48),1);}private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}
}
