package com.alfa.device_ctrl;

import java.io.*;
import java.net.HttpURLConnection;
import java.net.URL;
import java.net.URLConnection;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.security.MessageDigest;
import java.util.*;
import java.util.zip.GZIPInputStream;
import org.tukaani.xz.XZInputStream;

/** Installs one verified ARM64 rootless runtime from the canonical runtime registry. */
public final class RuntimeInstaller {
    public static final String SCHEMA_VERSION="runtime-ready.v1";
    public static final String TRUSTED_PROOT_ARM64_SHA256="c902f35b3bce4013d2e78e3bf360b606523d55ab7b907578938577b243bfca38";
    public static final String TRUSTED_PROOT_LOADER_ARM64_SHA256="b165c63ef14d274ddc7bc83e1e624fbb566d8cbd4a95a1d1891c7c6d8fd04baa";
    private static final int TAR_BLOCK=512;
    public interface Progress{void onMessage(String message);} interface SmokeRunner{String run(File engine,File root);}
    public static final class Result{public final boolean success;public final String runtimeId;public final String message;public final File runtimeDirectory;private Result(boolean s,String id,String m,File d){success=s;runtimeId=id;message=m;runtimeDirectory=d;}public static Result ok(String id,File d){return new Result(true,id,"READY",d);}public static Result fail(String id,String m,File d){return new Result(false,id,m,d);}}
    private final File vault,packagedEngine,nativeLibraryDir;private final Progress progress;private final SmokeRunner smokeRunner;
    public RuntimeInstaller(File vault,Progress progress){this(vault,progress,null,null,RuntimeInstaller::runRuntimeSmokeTest);}public RuntimeInstaller(File vault,Progress progress,File engine,File lib){this(vault,progress,engine,lib,RuntimeInstaller::runRuntimeSmokeTest);}
    RuntimeInstaller(File vault,Progress progress,File engine,File lib,SmokeRunner smoke){if(vault==null||vault.getAbsolutePath().startsWith("/home/userland"))throw new IllegalArgumentException("vault is outside Alfa boundary");this.vault=vault;this.progress=progress;this.packagedEngine=engine;this.nativeLibraryDir=lib;this.smokeRunner=smoke==null?RuntimeInstaller::runRuntimeSmokeTest:smoke;}
    public Result install(String runtimeId,URL ignoredEngineUrl,String engineSha256,URL archiveUrl,String archiveSha256,boolean gzip){if(RuntimeRegistry.get(runtimeId)==null)return Result.fail(runtimeId,"unsupported-runtime-id",null);if(!validToken(runtimeId)||archiveUrl==null||!validSha(engineSha256)||!validSha(archiveSha256))return Result.fail(runtimeId,"invalid-install-request",null);return installInternal(runtimeId,engineSha256,archiveUrl,archiveSha256,gzip);}
    public Result install(RuntimeProfile profile,URL ignoredEngineUrl,String engineSha256,URL archiveUrl,String archiveSha256,boolean gzip){if(profile==null||RuntimeRegistry.get(profile.id())!=profile)return Result.fail(profile==null?null:profile.id(),"unsupported-runtime-profile",null);if(archiveUrl==null||!profile.rootfsUrl().equals(archiveUrl.toString())||!profile.rootfsSha256().equalsIgnoreCase(archiveSha256)||profile.rootfsGzip()!=gzip)return Result.fail(profile.id(),"runtime-artifact-does-not-match-registry",null);return installInternal(profile.id(),engineSha256,archiveUrl,archiveSha256,gzip);}
    private Result installInternal(String runtimeId,String engineSha256,URL archiveUrl,String archiveSha256,boolean gzip){File runtime=new File(vault,"runtimes/"+runtimeId),staging=new File(vault,".staging/"+runtimeId+"."+UUID.randomUUID()),root=new File(staging,"rootfs");try{report("INSTALL_STAGE_CREATED");if(packagedEngine==null||nativeLibraryDir==null)throw new IOException("packaged-engine-required");if(!staging.mkdirs()||!root.mkdirs())throw new IOException("cannot-create-staging");File tmp=new File(staging,"proot_tmp");if(!tmp.mkdirs())throw new IOException("cannot-create-proot-tmp");File cs=staging.getCanonicalFile(),ct=tmp.getCanonicalFile();if(!ct.toPath().startsWith(cs.toPath()))throw new IOException("proot-tmp-outside-staging");if(!ct.isDirectory()||!ct.canWrite()||!ct.canExecute())throw new IOException("proot-tmp-not-usable");report("PROOT_TMP_DIR_READY");if(!TRUSTED_PROOT_ARM64_SHA256.equalsIgnoreCase(engineSha256))throw new IOException("runtime-engine-trusted-sha-mismatch");validatePackagedEngine(packagedEngine,nativeLibraryDir);validatePackagedLoader(packagedEngine,nativeLibraryDir);File archive=new File(staging,"rootfs.archive");downloadVerified(archiveUrl,archive,archiveSha256);extractTar(archive,root,gzip);validateRootfs(root,RuntimeRegistry.get(runtimeId));writeResolver(root);String smoke=smokeRunner.run(packagedEngine,root);if(smoke!=null)throw new IOException(smoke);publishAtomically(runtime,staging,runtimeId,packagedEngine,engineSha256,archiveSha256);deleteRecursively(new File(runtime,"rootfs.archive"));report("INSTALL_COMMITTED");return Result.ok(runtimeId,runtime);}catch(Exception e){report("INSTALL_FAILED "+e.getClass().getSimpleName());deleteRecursively(staging);return Result.fail(runtimeId,e.getClass().getSimpleName()+":"+String.valueOf(e.getMessage()),runtime);}}
    private void validatePackagedEngine(File engine,File lib)throws Exception{if(!engine.isFile())throw new IOException("runtime-engine-missing");if(!engine.getName().equals("libproot.so"))throw new IOException("runtime-engine-name-invalid");File ce=engine.getCanonicalFile(),cd=lib.getCanonicalFile(),parent=ce.getParentFile();if(parent==null||!cd.equals(parent))throw new IOException("runtime-engine-not-nativeLibraryDir");if(!ce.canExecute()||!isArm64Elf(ce))throw new IOException("runtime-engine-invalid");String actual=sha256(ce);if(!TRUSTED_PROOT_ARM64_SHA256.equalsIgnoreCase(actual))throw new IOException("runtime-engine-checksum-mismatch expected="+TRUSTED_PROOT_ARM64_SHA256+" actual="+actual);report("PACKAGED_ENGINE_VERIFIED");}
    private void validatePackagedLoader(File engine,File lib)throws Exception{File loader=new File(lib.getCanonicalFile(),"libproot-loader.so").getCanonicalFile();if(!loader.isFile()||!loader.canExecute()||!isArm64Elf(loader))throw new IOException("runtime-loader-invalid");String actual=sha256(loader);if(!RuntimeEvidence.isTrustedProotLoaderSha256(actual))throw new IOException("runtime-loader-checksum-mismatch actual="+actual);report("PACKAGED_LOADER_VERIFIED");}
    private static boolean isArm64Elf(File f)throws IOException{byte[]h=new byte[20];try(InputStream in=new FileInputStream(f)){int o=0,c;while(o<h.length&&(c=in.read(h,o,h.length-o))>0)o+=c;return o>=20&&(h[0]&255)==127&&h[1]=='E'&&h[2]=='L'&&h[3]=='F'&&(h[4]&255)==2&&(h[5]&255)==1&&(h[18]&255)==183&&(h[19]&255)==0;}}
    private void publishAtomically(File target,File staging,String id,File engine,String engineSha,String archiveSha)throws Exception{File parent=target.getParentFile();if(parent==null||(!parent.exists()&&!parent.mkdirs()))throw new IOException("runtime-parent-missing");File previous=new File(parent,target.getName()+".previous");deleteRecursively(previous);if(target.exists())moveDirectory(target.toPath(),previous.toPath());try{moveDirectory(staging.toPath(),target.toPath());File finalRoot=new File(target,"rootfs");writeReadyEvidence(target,id,engine,finalRoot,engineSha,archiveSha);if(!RuntimeEvidence.verify(new File(target,"READY.evidence"),id,engine,finalRoot))throw new IOException("ready-evidence-verification-failed");deleteRecursively(previous);}catch(Exception e){deleteRecursively(target);if(previous.exists())moveDirectory(previous.toPath(),target.toPath());throw e;}}
    private void downloadVerified(URL url,File dest,String expected)throws Exception{File tmp=new File(dest.getParentFile(),dest.getName()+".part");deleteRecursively(tmp);URLConnection c=url.openConnection();c.setConnectTimeout(30000);c.setReadTimeout(120000);if(c instanceof HttpURLConnection&&((HttpURLConnection)c).getResponseCode()!=HttpURLConnection.HTTP_OK)throw new IOException("HTTP-"+((HttpURLConnection)c).getResponseCode());MessageDigest d=MessageDigest.getInstance("SHA-256");try(InputStream in=new BufferedInputStream(c.getInputStream());OutputStream out=new BufferedOutputStream(new FileOutputStream(tmp))){byte[]b=new byte[65536];int n;while((n=in.read(b))!=-1){out.write(b,0,n);d.update(b,0,n);}}String actual=hex(d.digest());if(!expected.equalsIgnoreCase(actual)){deleteRecursively(tmp);throw new IOException("checksum-mismatch expected="+expected+" actual="+actual);}moveFile(tmp.toPath(),dest.toPath());}
    private void extractTar(File archive,File root,boolean gzip)throws Exception{try(InputStream raw=new BufferedInputStream(new FileInputStream(archive));InputStream in=gzip?new GZIPInputStream(raw):new XZInputStream(raw)){List<HardLink>links=new ArrayList<>();byte[]h=new byte[TAR_BLOCK];while(true){int n=readFull(in,h);if(n==0)break;if(n!=TAR_BLOCK)throw new EOFException("truncated-tar-header");if(isZeroBlock(h))break;String name=field(h,0,100),link=field(h,157,100);long size=octal(h,124,12);int type=h[156]&255;Path target=safeEntry(root.toPath(),name);if(type=='5')Files.createDirectories(target);else if(type=='2'||type=='1'){Path lt=type=='1'?safeHardLink(root.toPath(),link):safeLink(root.toPath(),target,link);Files.createDirectories(target.getParent());if(type=='2'){try{Path symlinkTarget=target.getParent().relativize(lt);Files.createSymbolicLink(target,symlinkTarget);}catch(FileAlreadyExistsException ignored){}}else links.add(new HardLink(target,lt));skipExact(in,size);}else if(type==0||type=='0'){Files.createDirectories(target.getParent());try(OutputStream out=new BufferedOutputStream(new FileOutputStream(target.toFile()))){copyExact(in,out,size);}applyMode(target.toFile(),h);}else skipExact(in,size);skipExact(in,(TAR_BLOCK-(size%TAR_BLOCK))%TAR_BLOCK);}for(HardLink l:links)materializeHardLink(l);}}
    private static final class HardLink{final Path entry,target;HardLink(Path e,Path t){entry=e;target=t;}}
    private void materializeHardLink(HardLink l)throws IOException{if(!Files.exists(l.target,LinkOption.NOFOLLOW_LINKS))throw new IOException("hardlink-target-missing");Files.createDirectories(l.entry.getParent());try{Files.createLink(l.entry,l.target);}catch(UnsupportedOperationException|IOException e){Files.copy(l.target,l.entry,StandardCopyOption.REPLACE_EXISTING,StandardCopyOption.COPY_ATTRIBUTES);}}
    private void validateRootfs(File root,RuntimeProfile profile)throws IOException{if(!root.isDirectory())throw new IOException("rootfs-missing");if(profile==null)throw new IOException("runtime-profile-missing");for(String entry:profile.requiredPaths())if(!new File(root,entry).exists())throw new IOException("rootfs-missing-"+entry);}
    private void writeResolver(File root)throws IOException{File r=new File(root,"etc/resolv.conf");if(r.exists()&&!r.delete())throw new IOException("resolver-replace-failed");File p=r.getParentFile();if(p==null||(!p.exists()&&!p.mkdirs()))throw new IOException("resolver-parent-missing");try(FileOutputStream out=new FileOutputStream(r)){out.write("# Alfa runtime default; network capability remains evidence-dependent.\nnameserver 1.1.1.1\nnameserver 8.8.8.8\n".getBytes(StandardCharsets.UTF_8));}}
    private static String runRuntimeSmokeTest(File engine,File root){Process p=null;try{if(!engine.isFile()||!engine.canExecute()||!root.isDirectory())return "runtime-smoke-input-invalid";File tmp=root.getParentFile()==null?null:new File(root.getParentFile(),"proot_tmp");if(tmp==null||!tmp.isDirectory()||!tmp.canWrite()||!tmp.canExecute())return "runtime-smoke-proot-tmp-not-usable";File loader=new File(engine.getParentFile(),"libproot-loader.so");if(!loader.isFile()||!loader.canExecute()||!isArm64Elf(loader)||!RuntimeEvidence.isTrustedProotLoaderSha256(sha256(loader)))return "runtime-smoke-loader-invalid";ProcessBuilder b=new ProcessBuilder(engine.getAbsolutePath(),"-0","-r",root.getAbsolutePath(),"-b","/dev","-b","/proc","-b","/sys","-w","/root","/usr/bin/env","-i","HOME=/root","PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin","TERM=xterm-256color","PROOT_TMP_DIR="+tmp.getAbsolutePath(),"/bin/sh","-c","printf 'ALFA_RUNTIME_SMOKE_OK\\n'; id -u; pwd");b.environment().put("PROOT_TMP_DIR",tmp.getAbsolutePath());b.environment().put("PROOT_LOADER",loader.getAbsolutePath());b.directory(root.getParentFile());b.redirectErrorStream(true);p=b.start();if(!p.waitFor(30,java.util.concurrent.TimeUnit.SECONDS)){p.destroyForcibly();return "runtime-smoke-timeout";}String out;try(InputStream in=p.getInputStream()){byte[]buf=new byte[4096];StringBuilder s=new StringBuilder();int n;while((n=in.read(buf))!=-1)s.append(new String(buf,0,n,StandardCharsets.UTF_8));out=s.toString();}if(p.exitValue()!=0)return "runtime-smoke-exit-"+p.exitValue()+":"+compact(out);if(!out.contains("ALFA_RUNTIME_SMOKE_OK")||!out.matches("(?s).*\\n0\\n/.*"))return "runtime-smoke-contract-mismatch:"+compact(out);return null;}catch(Exception e){if(p!=null)p.destroyForcibly();return "runtime-smoke-exec-"+e.getClass().getSimpleName()+":"+compact(e.getMessage());}}
    private static String compact(String v){if(v==null)return "";String n=v.replace('\n',' ').replace('\r',' ').trim();return n.length()>240?n.substring(0,240):n;}
    private void writeReadyEvidence(File staging,String id,File engine,File root,String engineSha,String archiveSha)throws Exception{Properties p=new Properties();p.setProperty("schema_version",SCHEMA_VERSION);p.setProperty("status","READY");p.setProperty("runtime_id",id);p.setProperty("engine_path",engine.getCanonicalPath());p.setProperty("engine_source","ApplicationInfo.nativeLibraryDir");p.setProperty("engine_abi","arm64-v8a");p.setProperty("rootfs_path",root.getCanonicalPath());p.setProperty("engine_sha256",engineSha.toLowerCase());p.setProperty("archive_sha256",archiveSha.toLowerCase());p.setProperty("smoke_contract","ALFA_RUNTIME_SMOKE_OK;uid=0;rootfs-pwd");p.setProperty("created_at_epoch_ms",Long.toString(System.currentTimeMillis()));try(FileOutputStream out=new FileOutputStream(new File(staging,"READY.evidence"))){p.store(out,"Alfa Device Ctrl runtime-ready.v1");}}
    private Path safeEntry(Path root,String name)throws IOException{if(name==null||name.isEmpty()||name.startsWith("/")||name.indexOf('\0')>=0)throw new IOException("unsafe-archive-path");Path r=root.resolve(name).normalize();if(!r.startsWith(root.normalize()))throw new IOException("archive-traversal");return r;}
    private Path safeHardLink(Path root,String link)throws IOException{if(link==null||link.isEmpty()||link.startsWith("/")||link.indexOf('\0')>=0)throw new IOException("unsafe-hardlink");Path r=root.resolve(link).normalize();if(!r.startsWith(root.normalize()))throw new IOException("hardlink-traversal");return r;}
    private Path safeLink(Path root,Path entry,String link)throws IOException{if(link==null||link.isEmpty()||link.indexOf('\0')>=0)throw new IOException("unsafe-link");Path r=link.startsWith("/")?root.resolve(link.substring(1)).normalize():entry.getParent().resolve(link).normalize();if(!r.startsWith(root.normalize()))throw new IOException("link-traversal");return r;}
    private void applyMode(File f,byte[]h){int mode=(int)octal(h,100,8);f.setReadable((mode&0444)!=0,false);f.setWritable((mode&0222)!=0,false);f.setExecutable((mode&0111)!=0,false);}
    private static String field(byte[]b,int o,int l){int e=o;while(e<o+l&&b[e]!=0)e++;return new String(b,o,e-o,StandardCharsets.UTF_8).trim();}
    private static long octal(byte[]b,int o,int l){long v=0;for(int i=o;i<o+l&&b[i]!=0;i++)if(b[i]>='0'&&b[i]<='7')v=(v<<3)+b[i]-'0';return v;}
    private static boolean isZeroBlock(byte[]b){for(byte v:b)if(v!=0)return false;return true;}private static int readFull(InputStream in,byte[]b)throws IOException{int o=0,n;while(o<b.length&&(n=in.read(b,o,b.length-o))>0)o+=n;return o;}private static void copyExact(InputStream in,OutputStream out,long size)throws IOException{byte[]b=new byte[65536];long left=size;while(left>0){int n=in.read(b,0,(int)Math.min(b.length,left));if(n<0)throw new EOFException("truncated-entry");out.write(b,0,n);left-=n;}}private static void skipExact(InputStream in,long size)throws IOException{long left=size;while(left>0){long n=in.skip(left);if(n<=0){if(in.read()<0)throw new EOFException("truncated-padding");n=1;}left-=n;}}
    private static void moveFile(Path a,Path b)throws IOException{Files.move(a,b,StandardCopyOption.REPLACE_EXISTING,StandardCopyOption.ATOMIC_MOVE);}private static void moveDirectory(Path a,Path b)throws IOException{Files.move(a,b,StandardCopyOption.ATOMIC_MOVE);}private static boolean validToken(String v){return v!=null&&v.matches("[A-Za-z0-9._-]{1,64}");}private static boolean validSha(String v){return v!=null&&v.matches("[0-9a-fA-F]{64}");}private static String sha256(File f)throws Exception{MessageDigest d=MessageDigest.getInstance("SHA-256");try(InputStream in=new BufferedInputStream(new FileInputStream(f))){byte[]b=new byte[65536];int n;while((n=in.read(b))!=-1)d.update(b,0,n);}return hex(d.digest());}private static String hex(byte[]b){StringBuilder o=new StringBuilder(b.length*2);for(byte v:b)o.append(String.format("%02x",v&255));return o.toString();}private void report(String m){if(progress!=null)progress.onMessage(m);}private static void deleteRecursively(File f){if(f==null||!f.exists())return;if(f.isDirectory()&&!Files.isSymbolicLink(f.toPath())){File[]c=f.listFiles();if(c!=null)for(File x:c)deleteRecursively(x);}f.delete();}
}
