package com.alfa.device_ctrl;

import android.content.ContentResolver;import android.content.Context;import android.content.Intent;import android.database.Cursor;import android.net.Uri;import android.provider.DocumentsContract;
import java.io.ByteArrayOutputStream;import java.io.FileNotFoundException;import java.io.InputStream;import java.io.OutputStream;import java.nio.charset.StandardCharsets;import java.util.ArrayList;import java.util.Collections;import java.util.List;

/** Canonical host-project access through SAF; settings are persisted by the canonical DataStore. */
public final class SafHostStorageProvider{
 private static final int MAX_TEXT_BYTES=1_048_576;private final Context context;private final ContentResolver resolver;public SafHostStorageProvider(Context c){context=c.getApplicationContext();resolver=context.getContentResolver();}
 public Intent createTreePickerIntent(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT_TREE);i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_WRITE_URI_PERMISSION|Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION|Intent.FLAG_GRANT_PREFIX_URI_PERMISSION);return i;}
 public boolean persistTreeUri(Uri uri){if(uri==null)return false;try{resolver.takePersistableUriPermission(uri,Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_WRITE_URI_PERMISSION);AlfaSettingsStore.get(context).setHostTreeUri(uri.toString());return hasPersistedAccess(uri);}catch(SecurityException e){return false;}}
 public Uri treeUri(){String value=AlfaSettingsStore.get(context).getHostTreeUri(null);return value==null?null:Uri.parse(value);}
 public boolean hasPersistedAccess(){Uri uri=treeUri();return uri!=null&&hasPersistedAccess(uri);}private boolean hasPersistedAccess(Uri uri){for(android.content.UriPermission p:resolver.getPersistedUriPermissions())if(uri.equals(p.getUri())&&p.isReadPermission()&&p.isWritePermission())return true;return false;}
 public List<Entry> list(Uri parent){if(parent==null)return Collections.emptyList();Uri children=DocumentsContract.buildChildDocumentsUriUsingTree(parent,DocumentsContract.getDocumentId(parent));List<Entry> entries=new ArrayList<>();String[] projection={DocumentsContract.Document.COLUMN_DOCUMENT_ID,DocumentsContract.Document.COLUMN_DISPLAY_NAME,DocumentsContract.Document.COLUMN_MIME_TYPE,DocumentsContract.Document.COLUMN_SIZE,DocumentsContract.Document.COLUMN_LAST_MODIFIED,DocumentsContract.Document.COLUMN_FLAGS};try(Cursor cursor=resolver.query(children,projection,null,null,DocumentsContract.Document.COLUMN_DISPLAY_NAME+" COLLATE NOCASE ASC")){if(cursor==null)return entries;int id=cursor.getColumnIndexOrThrow(DocumentsContract.Document.COLUMN_DOCUMENT_ID),name=cursor.getColumnIndexOrThrow(DocumentsContract.Document.COLUMN_DISPLAY_NAME),mime=cursor.getColumnIndexOrThrow(DocumentsContract.Document.COLUMN_MIME_TYPE),size=cursor.getColumnIndexOrThrow(DocumentsContract.Document.COLUMN_SIZE),modified=cursor.getColumnIndexOrThrow(DocumentsContract.Document.COLUMN_LAST_MODIFIED),flags=cursor.getColumnIndexOrThrow(DocumentsContract.Document.COLUMN_FLAGS);while(cursor.moveToNext()){String documentId=cursor.getString(id);entries.add(new Entry(DocumentsContract.buildDocumentUriUsingTree(parent,documentId),cursor.getString(name),cursor.getString(mime),cursor.isNull(size)?-1L:cursor.getLong(size),cursor.isNull(modified)?-1L:cursor.getLong(modified),cursor.getInt(flags)));}}return entries;}
 public String readUtf8(Uri uri)throws Exception{if(uri==null)throw new IllegalArgumentException("documentUri");try(InputStream in=resolver.openInputStream(uri)){if(in==null)throw new FileNotFoundException(uri.toString());ByteArrayOutputStream out=new ByteArrayOutputStream();byte[] buffer=new byte[8192];int total=0,count;while((count=in.read(buffer))!=-1){total+=count;if(total>MAX_TEXT_BYTES)throw new IllegalArgumentException("file-too-large");out.write(buffer,0,count);}return new String(out.toByteArray(),StandardCharsets.UTF_8);}}
 public void writeUtf8(Uri uri,String content)throws Exception{if(uri==null)throw new IllegalArgumentException("documentUri");byte[] bytes=content==null?new byte[0]:content.getBytes(StandardCharsets.UTF_8);if(bytes.length>MAX_TEXT_BYTES)throw new IllegalArgumentException("file-too-large");try(OutputStream out=resolver.openOutputStream(uri,"wt")){if(out==null)throw new FileNotFoundException(uri.toString());out.write(bytes);out.flush();}}
 public Uri createDirectory(Uri parent,String name)throws Exception{validateName(name);return DocumentsContract.createDocument(resolver,parent,DocumentsContract.Document.MIME_TYPE_DIR,name);}public Uri createTextFile(Uri parent,String name)throws Exception{validateName(name);return DocumentsContract.createDocument(resolver,parent,"text/plain",name);}public boolean delete(Uri uri)throws Exception{return uri!=null&&DocumentsContract.deleteDocument(resolver,uri);}private static void validateName(String name){if(name==null||name.trim().isEmpty()||name.contains("/")||name.contains("\\")||".".equals(name)||"..".equals(name))throw new IllegalArgumentException("invalid-document-name");}
 public static final class Entry{public final Uri uri;public final String name,mimeType;public final long size,modifiedEpochMs;public final int flags;Entry(Uri u,String n,String m,long s,long mod,int f){uri=u;name=n;mimeType=m;size=s;modifiedEpochMs=mod;flags=f;}public boolean isDirectory(){return DocumentsContract.Document.MIME_TYPE_DIR.equals(mimeType);}}
}
