package com.alfa.device_ctrl;

/** Generated from the supplied Stitch v1 reference ZIP. This is a mapping/provenance catalog, not copied UI source. */
public final class StitchV1ReferenceCatalog {
    public static final String ZIP_SHA256 = "7b3428e474e7c778a11fecf995d417bc1b6d5d9575a879fa9da1e86eb637895d";
    public static final String CANONICAL_PACKAGE = "com.alfa.device_ctrl";
    public static final String CANONICAL_HOST_ROOT = "/sdcard/Alfa_device_ctrl_HOST";
    private static final String[] SCREEN_IDS = new String[] {
        "alfa_device_ctrl_operational_terminal_runtime_dashboard",
        "alfa_device_ctrl_security_diagnostic_console",
        "alfa_device_ctrl_harden_bind_remediation_dialog_1",
        "alfa_device_ctrl_harden_bind_remediation_dialog_2",
        "alfa_device_ctrl_mount_isolation_policy_settings",
        "alfa_device_ctrl_add_directory_override_dialog",
        "alfa_device_ctrl_host_directory_browser_dialog",
        "alfa_device_ctrl_create_new_folder_dialog",
        "alfa_device_ctrl_unlink_directory_override_dialog",
        "alfa_device_ctrl_edit_override_permissions_dialog",
        "alfa_device_ctrl_sensitive_files_permission_warning_dialog",
        "alfa_device_ctrl_mount_isolation_policy_settings_masked_status",
        "alfa_device_ctrl_terminal.env_access_simulation",
        "alfa_device_ctrl_terminal_su_escalation_blocked_simulation",
        "alfa_device_ctrl_terminal_ld_preload_ptrace_bypass_blocked",
        "alfa_device_ctrl_reset_runtime_policy_confirmation_dialog",
        "alfa_device_ctrl_export_policy_backup_json_dialog",
        "alfa_device_ctrl_import_restore_policy_backup_json_dialog",
        "alfa_device_ctrl_import_policy_backup_with_profile_presets",
        "alfa_device_ctrl_policy_restore_processing_state",
        "alfa_device_ctrl_policy_successfully_restored_applied",
        "alfa_device_ctrl_shizuku_rish_propagation_audit_log",
        "alfa_device_ctrl_audit_log_seccomp_mount_filtered",
        "alfa_device_ctrl_syscall_trap_verification_dialog",
        "alfa_device_ctrl_export_seccomp_bpf_audit_report_json",
        "alfa_device_ctrl_file_browser_sdcard_alfactrl_audits",
        "alfa_device_ctrl_share_audit_file_android_share_sheet",
        "alfa_device_ctrl_termux_termux_open_ingestion_simulation",
        "alfa_device_ctrl_matrix_ops_bot_webhook_notification_dispatch",
        "alfa_device_ctrl_matrix_webhook_event_dispatched_success",
        "alfa_device_ctrl_matrix_webhook_dispatch_failure_retry_handling",
        "alfa_device_ctrl_pengaturan_bahasa_interaksi_bahasa_indonesia",
        "alfa_device_ctrl_language_selector_dialog_switch_confirmation",
        "alfa_device_ctrl_settings_interaction_language_tablet_desktop_view",
        "alfa_device_ctrl_interaction_language_settings_english_selected",
        "alfa_device_ctrl_project_explorer_workspace_tablet_desktop_view",
        "alfa_device_ctrl_project_explorer_slide_out_drawer_mobile_view",
        "alfa_device_ctrl_project_explorer_delete_file_confirmation_dialog",
        "alfa_device_ctrl_project_explorer_recursive_directory_delete_confirmation_dialog",
        "alfa_device_ctrl_project_explorer_folder_context_menu_tablet_desktop_view",
        "alfa_device_ctrl_create_new_file_folder_dialog_in_tools_desktop_view",
        "alfa_device_ctrl_create_new_folder_dialog_in_tools_desktop_view",
        "alfa_device_ctrl_folder_audit_scripts_created_in_tools_desktop_view_1",
        "alfa_device_ctrl_folder_audit_scripts_created_in_tools_desktop_view_2",
        "alfa_device_ctrl_primary_app_icon",
        "alfa_device_ctrl_app_icon_suite_presentation",
        "alfa_device_ctrl_alpine_linux_3.24.1_active_runtime_terminal",
        "alfa_device_ctrl_ubuntu_24.04.4_lts_active_runtime_terminal",
        "alfa_device_ctrl_kali_nethunter_rootless_active_runtime_terminal",
        "alfa_device_ctrl_project_explorer_kali_vfs_usr_share_nmap",
        "alfa_device_ctrl_project_explorer_vfs_comparison_ubuntu_vs_kali",
        "alfa_device_ctrl_split_pane_terminal_workspace_ubuntu_vs_kali",
        "alfa_device_ctrl_split_pane_terminal_sync_input_active",
        "alfa_device_ctrl_split_pane_terminal_ubuntu_focused_sync_off",
        "alfa_device_ctrl_split_pane_terminal_horizontal_split_horiz",
        "alfa_device_ctrl_split_pane_terminal_vertical_split_vert_ubuntu_focused",
        "alfa_device_ctrl_split_pane_terminal_sync_input_dual_broadcast_active",
        "alfa_device_ctrl_floating_terminal_overlay_permission_request",
        "alfa_device_ctrl_floating_terminal_window_over_android_application",
        "alfa_device_ctrl_floating_terminal_minimized_bubble_mode",
        "alfa_device_ctrl_floating_terminal_controls_session_lifecycle",
        "alfa_device_ctrl_floating_terminal_virtual_keyboard_ime_active_1",
        "alfa_device_ctrl_floating_keyboard_bar_opacity_size_settings",
        "alfa_device_ctrl_floating_terminal_interactive_view_ime_active",
        "alfa_device_ctrl_floating_terminal_opacity_window_size_settings_1",
        "alfa_device_ctrl_floating_terminal_interactive_view_90_opacity_applied_1",
        "alfa_device_ctrl_floating_terminal_restored_to_window_view_1",
        "alfa_device_ctrl_floating_terminal_opacity_window_size_settings_2",
        "alfa_device_ctrl_floating_terminal_interactive_view_90_opacity_applied_2",
        "alfa_device_ctrl_floating_terminal_virtual_keyboard_ime_active_2",
        "alfa_device_ctrl_floating_terminal_command_executed_tunnel_output",
        "alfa_device_ctrl_floating_terminal_sigint_c_tunnel_daemon_stopped",
        "alfa_device_ctrl_floating_terminal_screen_cleared_clear_command_executed",
        "alfa_device_ctrl_floating_terminal_uname_a_ls_la_executed",
        "alfa_device_ctrl_floating_terminal_keyboard_dismissed_resting_view",
        "alfa_device_ctrl_floating_terminal_minimized_to_bubble_mode",
        "alfa_device_ctrl_floating_terminal_restored_to_window_view_2",
        "alfa_device_ctrl_appearance_typography_settings_mobile_view",
        "alfa_device_ctrl_appearance_typography_settings_tablet_desktop_2_pane_view",
        "alfa_device_ctrl_terminal_font_picker_appearance_mobile_view",
        "alfa_device_ctrl_reset_appearance_confirmation_dialog",
        "alfa_device_ctrl_appearance_settings_obsidian_cyan_preset_active",
        "alfa_device_ctrl_appearance_settings_compact_density_large_font",
        "alfa_device_ctrl_appearance_settings_restored_to_default_density_font",
        "alfa_device_ctrl_terminal_font_picker_jetbrains_mono_fira_code",
        "alfa_device_ctrl_appearance_settings_fira_code_pty_font_applied",
        "alfa_device_ctrl_operational_terminal_runtime_dashboard_fira_code_active",
        "alfa_device_ctrl_operational_terminal_with_project_explorer_opened_right_drawer",
        "alfa_device_ctrl_create_new_file_dialog_in_audit_scripts",
        "alfa_device_ctrl_create_new_file_dialog_python.py_selected",
        "alfa_device_ctrl_text_editor_start_tunnel.sh_opened",
        "alfa_device_ctrl_terminal_start_tunnel.sh_executed_in_pts_0",
        "alfa_device_ctrl_security_diagnostic_console_socket_connection_status_active",
        "alfa_device_ctrl_security_diagnostic_console_alfa_engine.sock_drop_reconnect",
        "alfa_device_ctrl_security_diagnostic_console_socket_rebind_success_fd_10",
        "alfa_device_ctrl_15_session_multiplexer_ubuntu_kali_alpine_mobile_view",
        "alfa_device_ctrl_kali_nethunter_active_terminal_session_07_of_15",
        "alfa_device_ctrl_ubuntu_24.04_lts_active_terminal_session_03_of_15",
        "alfa_device_ctrl_alpine_linux_active_terminal_session_11_of_15",
        "alfa_device_ctrl_ubuntu_terminal_sessions_3_10_active_manager",
        "alfa_device_ctrl_ubuntu_maximum_sessions_reached_10_10_limit",
        "alfa_device_ctrl_stop_session_confirmation_lifecycle_dialog",
        "alfa_device_ctrl_floating_terminal_session_switcher_ubuntu_s1_s2",
        "alfa_device_ctrl_floating_terminal_switched_to_ubuntu_session_1_pts_0",
        "alfa_device_ctrl_ubuntu_terminal_sessions_spawned_session_3_pts_2",
        "alfa_device_ctrl_ubuntu_terminal_sessions_spawned_session_4_pts_3_make_j4",
        "alfa_device_ctrl_ubuntu_terminal_sessions_spawned_session_5_pts_4_nmap_tcpdump",
        "alfa_device_ctrl_stop_session_5_confirmation_dialog_ubuntu_pts_4_1",
        "alfa_device_ctrl_stop_session_5_confirmation_dialog_sigkill_force_kill_1",
        "alfa_device_ctrl_ubuntu_terminal_sessions_spawned_session_6_pts_5_pytest_suite",
        "alfa_device_ctrl_ubuntu_terminal_sessions_switched_to_session_5_pts_4",
        "alfa_device_ctrl_stop_session_5_confirmation_dialog_ubuntu_pts_4_2",
        "alfa_device_ctrl_stop_session_5_confirmation_dialog_sigkill_force_kill_2",
        "alfa_device_ctrl_stop_session_5_confirmation_dialog_sigterm_15_default",
        "alfa_device_ctrl_ubuntu_terminal_sessions_session_5_terminated_via_sigterm",
        "alfa_device_ctrl_floating_terminal_monitoring_session_6_pts_5_pytest",
        "alfa_device_ctrl_floating_terminal_minimized_to_bubble_mode_session_6_pts_5",
        "alfa_device_ctrl_floating_terminal_restored_to_window_view_session_6_pts_5",
        "alfa_device_ctrl_ubuntu_terminal_session_manager_all_5_active_sessions",
        "alfa_device_ctrl_appearance_settings_mobile_vs_desktop_2_pane_comparison",
        "alfa_device_ctrl_terminal_font_picker_desktop_2_pane_view",
        "alfa_device_ctrl_terminal_typography_line_height_audit_split_tty_preview",
        "alfa_device_ctrl_operational_terminal_workstation_master_production_polish",
        "alfa_device_ctrl_floating_terminal_window_system_overlay_master_production",
        "alfa_device_ctrl_appearance_settings_high_contrast_aaa_preset_active",
        "alfa_device_ctrl_terminal_font_picker_fira_code_in_high_contrast_aaa_theme",
        "alfa_device_ctrl_appearance_settings_fira_code_persisted_to_datastore_proto",
        "alfa_device_ctrl_terminal_pts_0_fira_code_ligature_testing_active",
        "alfa_device_ctrl_appearance_settings_datastore_proto_active_configuration",
        "alfa_device_ctrl_appearance_settings_terminal_obsidian_preset_restored",
        "alfa_device_ctrl_terminal_font_picker_terminal_obsidian_theme",
        "alfa_device_ctrl_terminal_font_picker_fira_code_bold_700_active",
        "alfa_device_ctrl_appearance_settings_fira_code_bold_700_persisted_to_datastore",
        "alfa_device_ctrl_operational_terminal_workstation_refined_industrial_console",
        "alfa_device_ctrl_floating_terminal_ime_active_viewport",
        "alfa_device_ctrl_settings_control_center_refined_industrial_console",
        "alfa_device_ctrl_split_pane_workspace_session_manager",
        "alfa_device_ctrl_operational_terminal_workstation_high_contrast_aaa_theme",
        "alfa_device_ctrl_appearance_settings_contrast_profiles_theme_calibration",
        "alfa_device_ctrl_terminal_pts_0_max_glare_21_1_contrast_profile_active",
        "alfa_device_ctrl_split_pane_terminal_max_glare_21_1_contrast_profile_active",
        "alfa_device_ctrl_session_manager_spawn_new_terminal_session",
        "alfa_device_ctrl_active_ubuntu_terminal_spawned_session_pts_5",
        "alfa_device_ctrl_terminal_pts_5_apt_update_executed_in_ubuntu",
        "alfa_device_ctrl_terminal_pts_5_apt_upgrade_y_completed_in_ubuntu",
        "alfa_device_ctrl_terminal_pts_5_screen_cleared_via_clear_command",
        "alfa_device_ctrl_operational_terminal_selection_toolbar_refined_ui",
        "alfa_device_ctrl_split_pane_terminal_workspace_refined_ui",
        "alfa_device_ctrl_alfa_control_center_settings_refined_ui",
        "alfa_device_ctrl_floating_terminal_ime_viewport_refined_ui",
        "alfa_device_ctrl_split_pane_terminal_high_contrast_21_1_aaa_active",
        "alfa_device_ctrl_split_pane_terminal_horizontal_horiz_high_contrast_21_1_aaa",
        "alfa_device_ctrl_split_pane_terminal_vertical_split_vert_high_contrast_21_1_aaa",
        "alfa_device_ctrl_session_manager_kali_nethunter_target_selected",
        "alfa_device_ctrl_session_manager_cwd_home_kali_tools",
        "alfa_device_ctrl_session_manager_custom_exec_argument_configured",
        "alfa_device_ctrl_session_manager_flags_daemon_log_output_added",
        "alfa_device_ctrl_session_manager_split_viewport_vertical_dual_selected",
        "alfa_device_ctrl_session_manager_attach_active_pane_restored"
    };
    private StitchV1ReferenceCatalog() {}
    public static String[] screenIds() { return SCREEN_IDS.clone(); }
    public static boolean contains(String id) { if (id == null) return false; for (String v : SCREEN_IDS) if (v.equals(id)) return true; return false; }
    public static String category(String id) {
        if (id == null) return "unknown"; String s=id.toLowerCase();
        if (s.contains("security") || s.contains("seccomp") || s.contains("shizuku") || s.contains("su_escalation") || s.contains("ptrace")) return "security";
        if (s.contains("network") || s.contains("socket") || s.contains("tunnel") || s.contains("matrix")) return "network";
        if (s.contains("mount") || s.contains("override") || s.contains("sensitive_files") || s.contains("policy")) return "storage-policy";
        if (s.contains("project") || s.contains("file_browser") || s.contains("create_new_file") || s.contains("create_new_folder") || s.contains("directory")) return "project-storage";
        if (s.contains("appearance") || s.contains("font") || s.contains("language") || s.contains("settings")) return "settings";
        if (s.contains("split")) return "split";
        if (s.contains("floating")) return "floating";
        if (s.contains("session")) return "sessions";
        if (s.contains("runtime")) return "runtime";
        if (s.contains("terminal") || s.contains("operational")) return "terminal";
        return "other";
    }
    public static int size() { return SCREEN_IDS.length; }
}
