package com.alfa.device_ctrl;

import android.app.Activity;
import android.content.Intent;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.os.Bundle;
import android.view.Gravity;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.FrameLayout;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import com.termux.terminal.TerminalSession;
import com.termux.view.TerminalView;
import java.io.File;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.UUID;

/** Canonical Stitch v1 DUT surface: native windows + real runtime PTY. */
public final class StitchOperationalActivity extends Activity {
    private static final int BG=Color.rgb(16,20,25),SURFACE=Color.rgb(28,32,37),HIGH=Color.rgb(38,42,48);
    private static final int TEXT=Color.rgb(224,226,234),MUTED=Color.rgb(187,202,191),GREEN=Color.rgb(78,222,163),CYAN=Color.rgb(76,215,246),RED=Color.rgb(255,180,171);
    private static final String PROOT_SHA256="c902f35b3bce4013d2e78e3bf360b606523d55ab7b907578938577b243bfca38"; private static final int GATE6=702;
    private RuntimeProfile selectedRuntime; private final RuntimeSessionMultiplexer sessionMultiplexer=new RuntimeSessionMultiplexer(); private final Map<String,RuntimeSessionManager.Listener> sessionListeners=new LinkedHashMap<>(); private String selectedSessionId="SESSION_A"; private TerminalView terminal; private TextView systemState,sessionState,terminalState,telemetry,status; private LinearLayout nodePage,lanePage,diagPage; private boolean active;
    @Override protected void onCreate(Bundle state){super.onCreate(state);selectedRuntime=RuntimeSelection.profile(getPreferences(MODE_PRIVATE).getString("runtime_id",RuntimeSelection.DEFAULT_RUNTIME_ID));if(selectedRuntime==null)selectedRuntime=RuntimeSelection.profile(RuntimeSelection.DEFAULT_RUNTIME_ID);getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(Color.rgb(10,14,19));setContentView(build());active=true;refreshNodes();}
    @Override protected void onStart(){super.onStart();active=true;for(String id:sessionMultiplexer.sessionIds()){RuntimeSessionManager manager=sessionMultiplexer.getSession(id);RuntimeSessionManager.Listener listener=sessionListeners.get(id);if(manager!=null&&listener!=null)manager.rebindListener(listener);}attachSelectedSessionIfRunning();refreshNodes();}
    @Override protected void onStop(){active=false;sessionMultiplexer.stopAll();super.onStop();}
    @Override protected void onDestroy(){active=false;sessionMultiplexer.stopAll();super.onDestroy();}
    @Override protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(r==GATE6&&c==RESULT_OK)startSession();}
    private View build(){LinearLayout root=col(BG);root.addView(header(),new LinearLayout.LayoutParams(-1,dp(76)));root.addView(topStatus(),new LinearLayout.LayoutParams(-1,dp(38)));FrameLayout pages=new FrameLayout(this);pages.addView(buildNodes());pages.addView(buildLanes());pages.addView(buildDiagnostics());root.addView(pages,new LinearLayout.LayoutParams(-1,0,1));root.addView(bottomNav(),new LinearLayout.LayoutParams(-1,dp(58)));return root;}
    private View header(){LinearLayout r=row(BG);r.setPadding(dp(14),dp(8),dp(10),0);LinearLayout t=col(BG);t.addView(txt("ALFA::CTRL",GREEN,18,true));t.addView(txt("Linux Runtime Control",MUTED,11,false));r.addView(t,new LinearLayout.LayoutParams(0,dp(66),1));LinearLayout s=row(HIGH);s.setGravity(Gravity.CENTER);s.addView(txt("● ",GREEN,10,true));systemState=txt("SYSTEM ONLINE",GREEN,10,true);s.addView(systemState);r.addView(s,new LinearLayout.LayoutParams(dp(128),dp(34)));return r;}
    private View topStatus(){LinearLayout r=row(SURFACE);r.setPadding(dp(12),0,dp(12),0);sessionState=txt("PTY: OFFLINE",MUTED,10,true);r.addView(sessionState,new LinearLayout.LayoutParams(0,dp(38),1));r.addView(txt("4 RUNTIMES  //  NATIVE  //  NO WEBVIEW",MUTED,9,true));return r;}
    private View buildNodes(){nodePage=col(BG);nodePage.addView(window("NODES // LINUX RUNTIMES",runtimeWindowContent()));nodePage.addView(sp(8));nodePage.addView(window("NODE PROVENANCE",provenanceContent()));return nodePage;}
    private View buildLanes(){lanePage=col(BG);lanePage.setVisibility(View.GONE);lanePage.addView(window("LANE 01 // INTERACTIVE PTY",terminalWindowContent()),new LinearLayout.LayoutParams(-1,0,1));lanePage.addView(sp(8));lanePage.addView(window("LANE 02 // EXECUTION",executionContent()));return lanePage;}
    private View buildDiagnostics(){diagPage=col(BG);diagPage.setVisibility(View.GONE);diagPage.addView(window("DIAGNOSTICS // LIVE EVIDENCE",diagnosticContent()));diagPage.addView(sp(8));diagPage.addView(window("STATE MACHINE",stateContent()));return diagPage;}
    private View window(String title,View content){LinearLayout w=col(SURFACE);w.setBackground(round(SURFACE,8,Color.rgb(60,72,67)));LinearLayout bar=row(HIGH);bar.setGravity(Gravity.CENTER_VERTICAL);bar.setPadding(dp(8),0,dp(5),0);bar.addView(txt(title,GREEN,10,true),new LinearLayout.LayoutParams(0,dp(40),1));Button min=btn("—",MUTED,null);min.setOnClickListener(v->toggleWindowContent(content,min));Button max=btn("□",CYAN,null);max.setOnClickListener(v->toggleMax(w,content,max));Button close=btn("×",RED,v->w.setVisibility(View.GONE));bar.addView(min,new LinearLayout.LayoutParams(dp(40),dp(40)));bar.addView(max,new LinearLayout.LayoutParams(dp(40),dp(40)));bar.addView(close,new LinearLayout.LayoutParams(dp(40),dp(40)));w.addView(bar);w.addView(content,new LinearLayout.LayoutParams(-1,0,1));return w;}
    private void toggleWindowContent(View content,Button button){boolean hidden=content.getVisibility()!=View.VISIBLE;content.setVisibility(hidden?View.VISIBLE:View.GONE);button.setText(hidden?"—":"+");}
    private void toggleMax(LinearLayout w,View content,Button button){boolean max="RESTORE".equals(button.getText().toString());LinearLayout.LayoutParams p=(LinearLayout.LayoutParams)w.getLayoutParams();if(max){p.height=dp(220);p.weight=0;button.setText("□");}else{p.height=0;p.weight=1;button.setText("RESTORE");}w.setLayoutParams(p);content.setVisibility(View.VISIBLE);}
    private View runtimeWindowContent(){LinearLayout box=col(SURFACE);ScrollView scroll=new ScrollView(this);LinearLayout list=col(SURFACE);scroll.addView(list);box.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));return box;}
    private View provenanceContent(){LinearLayout b=col(SURFACE);b.setPadding(dp(10),dp(8),dp(10),dp(8));b.addView(txt("Debian is the proven baseline: runtime-ready.v1 → PRoot → rootfs → interactive PTY.",TEXT,10,true));b.addView(txt("Ubuntu / Alpine / Kali use the same RuntimeRegistry + RuntimeInstaller + InteractiveSessionContract path.",MUTED,10,false));return b;}
    private View terminalWindowContent(){LinearLayout b=col(Color.rgb(10,14,19));LinearLayout head=row(HIGH);head.setGravity(Gravity.CENTER_VERTICAL);terminalState=txt(selectedSessionId+" // "+selectedRuntime.displayName(),GREEN,10,true);head.addView(terminalState,new LinearLayout.LayoutParams(0,dp(40),1));head.addView(btn("A",CYAN,v->switchSession("SESSION_A")),new LinearLayout.LayoutParams(dp(46),dp(40)));head.addView(btn("B",CYAN,v->switchSession("SESSION_B")),new LinearLayout.LayoutParams(dp(46),dp(40)));head.addView(btn("NEW",GREEN,v->createAndStartNextSession()),new LinearLayout.LayoutParams(dp(62),dp(40)));head.addView(btn("RESTART",GREEN,v->restart()),new LinearLayout.LayoutParams(dp(82),dp(40)));head.addView(btn("STOP",RED,v->stop()),new LinearLayout.LayoutParams(dp(64),dp(40)));b.addView(head);FrameLayout f=new FrameLayout(this);terminal=new TerminalView(this,null);terminal.setTerminalViewClient(new AlfaTerminalViewClient());f.addView(terminal,new FrameLayout.LayoutParams(-1,-1));TextView empty=txt("PTY output appears here after OPEN on a READY runtime.",MUTED,11,false);empty.setGravity(Gravity.CENTER);f.addView(empty,new FrameLayout.LayoutParams(-1,-1));f.setTag(empty);b.addView(f,new LinearLayout.LayoutParams(-1,0,1));LinearLayout actions=row(SURFACE);EditText input=new EditText(this);input.setSingleLine(true);input.setHint("command → PTY");input.setTextColor(TEXT);input.setHintTextColor(MUTED);input.setTypeface(Typeface.MONOSPACE);input.setTextSize(11);actions.addView(input,new LinearLayout.LayoutParams(0,dp(46),1));actions.addView(btn("SEND",GREEN,v->writePty(input.getText().toString())),new LinearLayout.LayoutParams(dp(72),dp(46)));actions.addView(btn("APT UPDATE",CYAN,v->writePty("apt update")),new LinearLayout.LayoutParams(dp(104),dp(46)));b.addView(actions);return b;}
    private View executionContent(){LinearLayout b=col(SURFACE);b.setPadding(dp(10),dp(8),dp(10),dp(8));b.addView(txt("Android Activity → RuntimeSessionMultiplexer → RuntimeSessionManager → PTY → PRoot → rootfs",TEXT,10,true));b.addView(btn("RUN PING",CYAN,v->writePty("ping -c 1 1.1.1.1")),new LinearLayout.LayoutParams(-1,dp(46)));b.addView(btn("RUN UTS PROBE",GREEN,v->writePty("uname -a && id && pwd")),new LinearLayout.LayoutParams(-1,dp(46)));return b;}
    private View diagnosticContent(){LinearLayout b=col(SURFACE);b.setPadding(dp(10),dp(8),dp(10),dp(8));telemetry=txt("CPU=--  MEM=--  STORAGE=--  NET=--",MUTED,11,true);b.addView(telemetry);status=txt("Evidence channel idle.",MUTED,10,false);status.setTypeface(Typeface.MONOSPACE);b.addView(status);b.addView(btn("REFRESH LIVE TELEMETRY",CYAN,v->refreshTelemetry()),new LinearLayout.LayoutParams(-1,dp(46)));b.addView(btn("CHECK RUNTIME",GREEN,v->refreshNodes()),new LinearLayout.LayoutParams(-1,dp(46)));return b;}
    private View stateContent(){LinearLayout b=col(SURFACE);b.setPadding(dp(10),dp(8),dp(10),dp(8));b.addView(txt("READY ⇒ OPEN only. INSTALL is structurally absent while READY.",GREEN,10,true));b.addView(txt("NOT_READY ⇒ INSTALL. READY ⇒ OPEN.",MUTED,10,false));return b;}
    private View bottomNav(){LinearLayout r=row(HIGH);r.setPadding(dp(8),dp(5),dp(8),dp(5));r.addView(btn("NODES",GREEN,v->showPage(nodePage)),new LinearLayout.LayoutParams(0,dp(48),1));r.addView(btn("LANES",CYAN,v->showPage(lanePage)),new LinearLayout.LayoutParams(0,dp(48),1));r.addView(btn("DIAGNOSTICS",MUTED,v->showPage(diagPage)),new LinearLayout.LayoutParams(0,dp(48),1));return r;}
    private void showPage(View page){nodePage.setVisibility(page==nodePage?View.VISIBLE:View.GONE);lanePage.setVisibility(page==lanePage?View.VISIBLE:View.GONE);diagPage.setVisibility(page==diagPage?View.VISIBLE:View.GONE);}
    private void refreshNodes(){if(nodePage==null)return;LinearLayout win=(LinearLayout)nodePage.getChildAt(0);LinearLayout content=(LinearLayout)win.getChildAt(1);ScrollView scroll=(ScrollView)content.getChildAt(0);LinearLayout list=(LinearLayout)scroll.getChildAt(0);list.removeAllViews();for(RuntimeProfile p:RuntimeRegistry.all())list.addView(runtimeCard(p),new LinearLayout.LayoutParams(-1,dp(58)));}
    private View runtimeCard(RuntimeProfile p){RuntimeUiState.Status s=runtimeStatus(p);StitchV1RuntimeStateMachine.State state=StitchV1RuntimeStateMachine.from(s);LinearLayout c=row(SURFACE);c.setGravity(Gravity.CENTER_VERTICAL);c.setPadding(dp(8),0,dp(4),0);c.addView(txt(p.displayName()+"\n"+p.id()+"  "+p.version(),TEXT,10,true),new LinearLayout.LayoutParams(0,dp(54),1));c.addView(txt(RuntimeUiState.label(s),s==RuntimeUiState.Status.READY?GREEN:MUTED,9,true),new LinearLayout.LayoutParams(dp(78),dp(54)));c.addView(btn("CHECK",MUTED,v->check(p)),new LinearLayout.LayoutParams(dp(62),dp(46)));if(StitchV1RuntimeStateMachine.showOpen(state))c.addView(btn("OPEN",GREEN,v->{selectedRuntime=p;startSession();}),new LinearLayout.LayoutParams(dp(66),dp(46)));else if(StitchV1RuntimeStateMachine.showInstall(state)){Button install=btn("INSTALL",GREEN,v->{selectedRuntime=p;install(p);});install.setEnabled(state!=StitchV1RuntimeStateMachine.State.VERIFYING);c.addView(install,new LinearLayout.LayoutParams(dp(72),dp(46)));}return c;}
    private RuntimeUiState.Status runtimeStatus(RuntimeProfile p){File root=new File(new File(getFilesDir(),"runtime-vault/runtimes"),p.id());return RuntimeUiState.resolve(p.id(),root,new File(root,"READY.evidence"),new File(getApplicationInfo().nativeLibraryDir,"libproot.so"),new File(root,"rootfs"));}
    private void check(RuntimeProfile p){RuntimeUiState.Status s=runtimeStatus(p);showStatus("CHECK "+p.id()+" = "+RuntimeUiState.label(s));refreshNodes();}
    private void startSession(){if(!active)return;if(!selectedRuntimeReady()){showStatus("RUNTIME NOT READY // "+selectedRuntime.displayName());return;}RuntimeSessionManager manager=sessionMultiplexer.getSession(selectedSessionId);if(manager==null){manager=createSession(selectedSessionId);}if(manager.isRunning()){sessionMultiplexer.setActiveSessionId(selectedSessionId);manager.attachTo(terminal);hideTerminalOverlay();showStatus("SESSION SWITCH // "+selectedSessionId);return;}if(!startManager(selectedSessionId,manager)){return;}sessionMultiplexer.setActiveSessionId(selectedSessionId);manager.attachTo(terminal);hideTerminalOverlay();showStatus("PTY READY // "+selectedSessionId+" // "+selectedRuntime.displayName());}
    private boolean selectedRuntimeReady(){File runtime=new File(new File(getFilesDir(),"runtime-vault"),"runtimes/"+selectedRuntime.id());return new File(runtime,"READY.evidence").isFile();}
    private RuntimeSessionManager createSession(String sessionId){File runtime=new File(new File(getFilesDir(),"runtime-vault"),"runtimes/"+selectedRuntime.id());File ready=new File(runtime,"READY.evidence");File launch=new File(new File(getFilesDir(),"runtime-vault"),"gate7-launch.properties");if(!Gate6LaunchContract.verify(launch,selectedRuntime.id())){Intent i=new Intent(this,Gate6ImportActivity.class);i.putExtra("runtime_id",selectedRuntime.id());startActivityForResult(i,GATE6);throw new IllegalStateException("gate7-launch-required");}File cwd=new File(new File(getFilesDir(),"session-cwd"),sessionId.toLowerCase());if(!cwd.exists()&&!cwd.mkdirs())throw new IllegalStateException("session-cwd-create-failed:"+sessionId);InteractiveSessionContract contract=new InteractiveSessionContract("session-"+sessionId.toLowerCase(),"request-"+id(),"run-"+id(),selectedRuntime.id(),ready,new File(getApplicationInfo().nativeLibraryDir,"libproot.so"),new File(runtime,"rootfs"),cwd,new String[]{"HOME=/root","TERM=xterm-256color","PS1=alfa:"+selectedRuntime.id()+":\\w\\$ ","PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin","PROOT_TMP_DIR="+new File(runtime,"proot_tmp").getAbsolutePath()});RuntimeSessionManager.Listener listener=sessionListener(sessionId);RuntimeSessionManager manager=sessionMultiplexer.createSession(sessionId,contract,listener);sessionListeners.put(sessionId,listener);return manager;}
    private RuntimeSessionManager.Listener sessionListener(final String sessionId){return new RuntimeSessionManager.Listener(){@Override public void onState(String s){handleSessionState(sessionId,s);}@Override public void onTextChanged(){if(sessionId.equals(selectedSessionId)&&active)runOnUiThread(()->{if(terminal!=null)terminal.invalidate();});}@Override public void onSessionFinished(int code){handleSessionFinished(sessionId,code);}};}
    private void handleSessionState(String sessionId,String state){if(!sessionId.equals(selectedSessionId))return;runOnUiThread(()->{if(sessionState!=null)sessionState.setText("PTY "+sessionId+": "+state);if(systemState!=null)systemState.setText(("READY".equals(state)||"RUNNING".equals(state))?"SYSTEM ONLINE":"SYSTEM WAITING");});}
    private void handleSessionFinished(String sessionId,int code){runOnUiThread(()->{if(sessionId.equals(selectedSessionId)&&sessionState!=null)sessionState.setText("PTY "+sessionId+": FINISHED "+code);});}
    private boolean startManager(String sessionId,RuntimeSessionManager manager){try{boolean started=sessionMultiplexer.startSession(sessionId,80,24,8,16);if(!started){showStatus("PTY START BLOCKED // "+sessionId);return false;}return true;}catch(RuntimeException e){showStatus("PTY START ERROR // "+sessionId+" // "+e.getClass().getSimpleName()+":"+e.getMessage());return false;}}
    private void switchSession(String sessionId){if(!active)return;try{if(!sessionMultiplexer.containsSession(sessionId))createSession(sessionId);sessionMultiplexer.setActiveSessionId(sessionId);selectedSessionId=sessionId;RuntimeSessionManager manager=sessionMultiplexer.activeSession();if(manager==null){showStatus("SESSION NOT FOUND // "+sessionId);return;}if(!manager.isRunning()){if(!startManager(sessionId,manager))return;}manager.attachTo(terminal);terminalState.setText(sessionId+" // "+selectedRuntime.displayName());hideTerminalOverlay();showStatus("SESSION SWITCH // "+sessionId+" // PID="+(manager.currentSession()==null?-1:manager.currentSession().getPid()));}catch(RuntimeException e){showStatus("SESSION SWITCH ERROR // "+sessionId+" // "+e.getMessage());}}
    private void createAndStartNextSession(){String next=sessionMultiplexer.containsSession("SESSION_A")&&!sessionMultiplexer.containsSession("SESSION_B")?"SESSION_B":"SESSION_A";switchSession(next);}
    private void attachSelectedSessionIfRunning(){RuntimeSessionManager manager=sessionMultiplexer.getSession(selectedSessionId);if(manager!=null&&manager.isRunning()&&terminal!=null)manager.attachTo(terminal);}
    private void installRuntime(){install(selectedRuntime);}
    private void hideTerminalOverlay(){if(terminal!=null&&terminal.getParent() instanceof FrameLayout){FrameLayout f=(FrameLayout)terminal.getParent();Object tag=f.getTag();if(tag instanceof View)((View)tag).setVisibility(View.GONE);}}
    private void restart(){stop();new android.os.Handler().postDelayed(this::startSession,250);} private void stop(){sessionMultiplexer.stopSession(selectedSessionId);if(sessionState!=null)sessionState.setText("PTY "+selectedSessionId+": STOP REQUESTED");}
    private void writePty(String command){if(command==null||command.trim().isEmpty())return;RuntimeSessionManager manager=sessionMultiplexer.activeSession();TerminalSession s=manager==null?null:manager.currentSession();if(s==null||!s.isRunning()){showStatus("PTY NOT READY // "+selectedSessionId);return;}byte[] bytes=(command+"\n").getBytes(StandardCharsets.UTF_8);s.write(bytes,0,bytes.length);showStatus("PTY WRITE // "+selectedSessionId+" // "+command);}
    private void refreshTelemetry(){RuntimeSessionManager manager=sessionMultiplexer.activeSession();if(manager==null||!manager.isPromptReady()){showStatus("TELEMETRY BLOCKED // PTY NOT READY");return;}manager.runRuntimeCommand("awk '/MemTotal:/{print \"MEM=\"$2}' /proc/meminfo; df -P / | awk 'NR==2{print \"STORAGE=\"$5}'",(out,code)->runOnUiThread(()->{telemetry.setText("EXIT="+code+"\\n"+out);status.setText(out);}));}
    private void showStatus(String s){if(status!=null)status.setText(s);if(diagPage!=null)showPage(diagPage);}
    private TextView txt(String s,int c,int z,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextColor(c);t.setTextSize(z);t.setGravity(Gravity.CENTER_VERTICAL);if(bold)t.setTypeface(Typeface.MONOSPACE,Typeface.BOLD);return t;}
    private Button btn(String s,int c,View.OnClickListener l){Button b=new Button(this);b.setText(s);b.setTextColor(c);b.setTextSize(10);b.setMinHeight(0);b.setMinWidth(0);b.setPadding(dp(4),0,dp(4),0);b.setTypeface(Typeface.MONOSPACE,Typeface.BOLD);b.setStateListAnimator(null);b.setBackground(round(HIGH,6,Color.rgb(60,72,67)));if(l!=null)b.setOnClickListener(l);return b;}
    private LinearLayout row(int c){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.HORIZONTAL);l.setBackgroundColor(c);return l;}private LinearLayout col(int c){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setBackgroundColor(c);return l;}private View sp(int h){View v=new View(this);v.setLayoutParams(new LinearLayout.LayoutParams(-1,dp(h)));return v;}private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}private GradientDrawable round(int c,int r,int stroke){GradientDrawable d=new GradientDrawable();d.setColor(c);d.setCornerRadius(dp(r));d.setStroke(dp(1),stroke);return d;}private String id(){return UUID.randomUUID().toString().replace("-","").substring(0,12);}
    private void install(RuntimeProfile p){showStatus("INSTALL "+p.displayName()+" // verifying...");new Thread(()->{RuntimeInstaller.Result r;try{File vault=new File(getFilesDir(),"runtime-vault");File nativeDir=new File(getApplicationInfo().nativeLibraryDir);r=new RuntimeInstaller(vault,m->runOnUiThread(()->showStatus("INSTALL // "+m)),new File(nativeDir,"libproot.so"),nativeDir).install(p,null,PROOT_SHA256,new URL(p.rootfsUrl()),p.rootfsSha256(),p.rootfsGzip());}catch(Exception e){r=RuntimeInstaller.Result.fail(p.id(),e.getClass().getSimpleName()+":"+e.getMessage(),null);}RuntimeInstaller.Result done=r;runOnUiThread(()->{showStatus(done.success?"INSTALL READY // "+done.runtimeId:"INSTALL FAILED // "+done.message);refreshNodes();});},"stitch-install").start();}
}