#!/usr/bin/env bash
set -euo pipefail
ROOT=$(CDPATH= cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." 2>/dev/null && pwd)
RUN_ID=${1:-}; AUTH_INPUT=${2:-}; OUTPUT=${3:-}; PROOT_EXEC=${4:-}; ROOTFS=${5:-}
blocked(){ printf '%s\n' 'G17_STATUS=BLOCKED' "G17_REASON=$1" >&2; return 1; }
die(){ blocked "$1"; exit 1; }
field(){ awk -F= -v k="$1" '$1==k {sub(/^[^=]*=/,"",$0); print; exit}' "$2"; }
[ -n "$RUN_ID" ] && [ -n "$AUTH_INPUT" ] && [ -n "$OUTPUT" ] && [ -n "$PROOT_EXEC" ] && [ -n "$ROOTFS" ] || die 'explicit run id, G16 authorization, output, PRoot executable, and guest rootfs are required'
[[ "$RUN_ID" =~ ^run_[0-9]{8}_[0-9]{6}_[0-9]+$ ]] || die 'invalid pipeline run id'
[ -f "$AUTH_INPUT" ] || die 'G16 authorization artifact missing'; [ -x "$PROOT_EXEC" ] || die 'explicit PRoot executable is missing or not executable'; [ -d "$ROOTFS" ] || die 'explicit guest rootfs is missing'
[ -x "$ROOTFS/bin/sh" ] || die 'guest rootfs /bin/sh is missing or not executable'; [ -f "$ROOTFS/etc/os-release" ] || die 'guest rootfs identity /etc/os-release missing'; [ -x "$ROOTFS/usr/bin/readlink" ] || die 'guest evidence tool /usr/bin/readlink is missing or not executable'
HEAD=$(git -C "$ROOT" rev-parse HEAD 2>/dev/null || true); [ -n "$HEAD" ] || die 'current Git HEAD unavailable'
A_SCHEMA=$(field schema_version "$AUTH_INPUT"); A_GATE=$(field gate "$AUTH_INPUT"); A_STATUS=$(field gate_status "$AUTH_INPUT"); A_AUTH=$(field authorization_status "$AUTH_INPUT"); A_ID=$(field authorization_id "$AUTH_INPUT"); A_RUN=$(field pipeline_run_id "$AUTH_INPUT"); A_SOURCE=$(field source_commit "$AUTH_INPUT"); A_G4=$(field gate4_contract_sha256 "$AUTH_INPUT"); A_PROFILE=$(field profile_sha256 "$AUTH_INPUT"); A_POLICY_SHA=$(field gate15_policy_sha256 "$AUTH_INPUT"); A_POLICY_ART=$(field gate15_artifact "$AUTH_INPUT"); A_G5_SHA=$(field gate5_authorization_sha256 "$AUTH_INPUT"); A_G5_ART=$(field gate5_authorization_artifact "$AUTH_INPUT"); A_REQUEST=$(field request_id "$AUTH_INPUT"); A_COMMAND=$(field command "$AUTH_INPUT"); A_SEMANTICS=$(field command_semantics "$AUTH_INPUT"); A_CMD_SHA=$(field command_sha256 "$AUTH_INPUT"); A_EXEC=$(field execution_status "$AUTH_INPUT"); A_AUTHORITY=$(field execution_authority "$AUTH_INPUT"); A_PATH=$(field execution_path "$AUTH_INPUT")
[ "$A_SCHEMA" = gate16-runtime-execution-authorization.v1 ] || die 'G16 schema invalid'; [ "$A_GATE" = gate16 ] || die 'G16 identity invalid'; [ "$A_STATUS" = PASS ] || die 'G16 is not PASS'; [ "$A_AUTH" = AUTHORIZED ] || die 'G16 authorization is not AUTHORIZED'
[ "$A_ID" = "authorization-$RUN_ID" ] || die 'G16 authorization identity mismatch'; [ "$A_RUN" = "$RUN_ID" ] || die 'G16 run mismatch'; [ "$A_SOURCE" = "$HEAD" ] || die 'G16 source is stale relative to current HEAD'
[[ "$A_G4" =~ ^[0-9a-fA-F]{64}$ ]] || die 'Gate 4 hash invalid'; [[ "$A_PROFILE" =~ ^[0-9a-fA-F]{64}$ ]] || die 'profile hash invalid'; [ -f "$A_POLICY_ART" ] || die 'referenced G15 policy artifact missing'; [ -f "$A_G5_ART" ] || die 'referenced Gate 5 authorization artifact missing'
[ "$(sha256sum "$A_POLICY_ART" | awk '{print $1}')" = "$A_POLICY_SHA" ] || die 'G15 policy hash mismatch'; [ "$(sha256sum "$A_G5_ART" | awk '{print $1}')" = "$A_G5_SHA" ] || die 'Gate 5 authorization hash mismatch'
[ "$A_REQUEST" = "pwd-request-$RUN_ID" ] || die 'request identity mismatch'; [ "$A_COMMAND" = pwd ] || die 'command is not exact pwd'; [ "$A_SEMANTICS" = POSIX_PWD ] || die 'command semantics invalid'; EXPECTED_COMMAND_SHA=$(printf '%s\n' pwd | sha256sum | awk '{print $1}'); [ "$A_CMD_SHA" = "$EXPECTED_COMMAND_SHA" ] || die 'command hash mismatch'
[ "$A_EXEC" = DEFERRED ] || die 'execution state is not DEFERRED'; [ "$A_AUTHORITY" = G17 ] || die 'execution authority is not G17'; [ "$A_PATH" = DEFERRED:G17 ] || die 'execution path is not DEFERRED:G17'
PROOT_SHA=$(sha256sum "$PROOT_EXEC" | awk '{print $1}'); ROOTFS_OS_SHA=$(sha256sum "$ROOTFS/etc/os-release" | awk '{print $1}'); GUEST_OS_ID=$(awk -F= '$1=="ID" {gsub(/"/,"",$2); print $2; exit}' "$ROOTFS/etc/os-release"); [ -n "$GUEST_OS_ID" ] || die 'guest rootfs ID missing'
[ -d /proc ] || die 'host /proc is required for guest process evidence'; mkdir -p "$ROOTFS/proc"
TMP_DIR=$(mktemp -d "${TMPDIR:-/tmp}/alfa-g17.XXXXXX") || die 'temporary execution directory unavailable'; trap 'rm -rf "$TMP_DIR"' EXIT HUP INT TERM; STDOUT_FILE="$TMP_DIR/stdout"; STDERR_FILE="$TMP_DIR/stderr"
# Instrumentation is attached to shell EXIT; the authorized guest command itself is exactly `pwd`.
GUEST_EVIDENCE_SCRIPT='trap '\''printf "__G17_PROC_EXE=%s\\n" "$(/usr/bin/readlink /proc/self/exe)"; printf "__G17_PROC_CWD=%s\\n" "$(/usr/bin/readlink /proc/self/cwd)"; printf "__G17_PROC_ROOT=%s\\n" "$(/usr/bin/readlink /proc/self/root)"; printf "__G17_PROC_PID=%s\\n" "$$"'\'' EXIT; pwd'
"$PROOT_EXEC" -r "$ROOTFS" -b /proc:/proc -w /root /bin/sh -c "$GUEST_EVIDENCE_SCRIPT" >"$STDOUT_FILE" 2>"$STDERR_FILE" & PROOT_PID=$!; HOST_TRACEE_PID=''
for _ in $(seq 1 500); do CHILDREN="/proc/$PROOT_PID/task/$PROOT_PID/children"; if [ -r "$CHILDREN" ]; then HOST_TRACEE_PID=$(awk '{print $1}' "$CHILDREN" 2>/dev/null || true); [ -n "$HOST_TRACEE_PID" ] && break; fi; sleep 0.001; done
wait "$PROOT_PID"; RETURN_CODE=$?; [ "$RETURN_CODE" -eq 0 ] || die "PRoot execution failed with return code $RETURN_CODE"
RESULT=$(awk '!/^__G17_PROC_/ {print}' "$STDOUT_FILE" | sed '/^$/d' | head -n 1); [ "$RESULT" = /root ] || die 'guest pwd result is not /root'
GUEST_PROC_EXE=$(sed -n 's/^__G17_PROC_EXE=//p' "$STDOUT_FILE" | sed -n '1p'); GUEST_PROC_CWD=$(sed -n 's/^__G17_PROC_CWD=//p' "$STDOUT_FILE" | sed -n '1p'); GUEST_PROC_ROOT=$(sed -n 's/^__G17_PROC_ROOT=//p' "$STDOUT_FILE" | sed -n '1p'); GUEST_INTERNAL_PID=$(sed -n 's/^__G17_PROC_PID=//p' "$STDOUT_FILE" | sed -n '1p')
[ -n "$GUEST_INTERNAL_PID" ] || die 'guest process PID evidence unavailable inside guest'; GUEST_PID="$GUEST_INTERNAL_PID"
[ -n "$GUEST_PROC_EXE" ] || die 'guest /proc/self/exe evidence unavailable'; [ -n "$GUEST_PROC_CWD" ] || die 'guest /proc/self/cwd evidence unavailable'; [ "$GUEST_PROC_CWD" = /root ] || die 'guest /proc/self/cwd is not /root'; [ -n "$GUEST_PROC_ROOT" ] || die 'guest /proc/self/root evidence unavailable'; [ "$GUEST_PROC_ROOT" != / ] || die 'guest /proc/self/root resolves to /'
NOW=$(date -u '+%Y-%m-%dT%H:%M:%SZ'); EXEC_SHA=$(printf '%s\n' "$RESULT" | sha256sum | awk '{print $1}'); AUTH_SHA=$(sha256sum "$AUTH_INPUT" | awk '{print $1}'); mkdir -p "$(dirname -- "$OUTPUT")" || die 'cannot create output directory'; TMP="$OUTPUT.partial.$$"
{ printf '%s\n' 'schema_version=gate17-runtime-execution.v1' 'gate=gate17' 'gate_status=PASS' "execution_id=execution-pwd-$RUN_ID" "pipeline_run_id=$RUN_ID" "source_commit=$HEAD" "gate4_contract_sha256=$A_G4" "profile_sha256=$A_PROFILE" "gate16_authorization_sha256=$AUTH_SHA" "gate16_authorization_artifact=$AUTH_INPUT" "request_id=$A_REQUEST" 'command=pwd' 'command_semantics=POSIX_PWD' "command_sha256=$EXPECTED_COMMAND_SHA" 'authorization_status=AUTHORIZED' 'execution_status=EXECUTED' 'result_status=PASS' "command_result=$RESULT" "command_returncode=$RETURN_CODE" "command_result_sha256=$EXEC_SHA" "engine_path=$PROOT_EXEC" "engine_sha256=$PROOT_SHA" "rootfs_path=$ROOTFS" "rootfs_os_id=$GUEST_OS_ID" "rootfs_os_release_sha256=$ROOTFS_OS_SHA" "guest_pid=$GUEST_PID" "guest_internal_pid=$GUEST_INTERNAL_PID" "host_tracee_pid=$HOST_TRACEE_PID" "guest_proc_exe=$GUEST_PROC_EXE" "guest_proc_cwd=$GUEST_PROC_CWD" "guest_proc_root=$GUEST_PROC_ROOT" "created_at=$NOW" 'execution_path=PRoot:-r:<rootfs>:-b:/proc:/proc:-w:/root:/bin/sh:-c:pwd' 'execution_reason=G16 authorization verified; exact pwd executed inside explicit PRoot guest rootfs; guest /proc/self evidence captured before shell exit'; } > "$TMP" || die 'failed to write execution evidence'; mv "$TMP" "$OUTPUT" || die 'failed to publish execution evidence'
printf '%s\n' 'G17_STATUS=PASS' 'G17_RESULT=EXECUTED' "G17_ARTIFACT=$OUTPUT" "COMMAND_RESULT=$RESULT" "COMMAND_RETURNCODE=$RETURN_CODE" "GUEST_PID=$GUEST_PID" "GUEST_INTERNAL_PID=$GUEST_INTERNAL_PID" "HOST_TRACEE_PID=$HOST_TRACEE_PID"
