#!/usr/bin/env bash
set -euo pipefail
T="app/src/androidTest/java/com/alfa/device_ctrl/G17AndroidRuntimeExecutionTest.java"
L="tools/test_gate17_live.sh"
B="app/build.gradle"
test -s "$T"
test -s "$B"
grep -Fq 'package com.alfa.device_ctrl.test;' "$T"
grep -Fq 'import com.alfa.device_ctrl.BuildConfig;' "$T"
grep -Fq 'InstrumentationRegistry.getInstrumentation().getTargetContext()' "$T"
grep -Fq 'android.os.Process.myUid()' "$T"
grep -Fq 'new ProcessBuilder(x)' "$T"
grep -Fq 'java.lang.Process p' "$T"
grep -Fq 'libproot.so' "$T"
grep -Fq 'gate16-runtime-execution-authorization.v1' "$T"
grep -Fq 'execution_status' "$T"
grep -Fq 'DEFERRED:G17' "$T"
grep -Fq 'BuildConfig.ALFA_SOURCE_COMMIT' "$T"
grep -Fq 'apk_source_commit=' "$T"
grep -Fq 'G17_LIVE_APK_SOURCE_COMMIT=' "$T"
grep -Fq "testNamespace 'com.alfa.device_ctrl.test'" "$B"
grep -Fq 'ALFA_SOURCE_COMMIT' "$B"
grep -Fq 'buildConfigField' "$B"
grep -Fq 'G17_LIVE_RESULT=REAL_ANDROID_DUT_EXECUTION' "$T"
! grep -Fq 'com.termux' "$T"
! grep -Fq '/home/userland' "$T"
! grep -Fq 'runtime_execution.sh' "$T"
! grep -Fq 'RuntimeSessionManager' "$T"
grep -Fq 'am instrument -w -r' "$L"
grep -Fq 'com.alfa.device_ctrl.test.G17AndroidRuntimeExecutionTest#exactGate16AuthorizationExecutesPwdInsidePackagedRuntime' "$L"
grep -Fq 'gate16_path' "$L"
grep -Fq 'run-as "$PACKAGE"' "$L"
grep -Fq 'APP_DATA_DIR=' "$L"
grep -Fq 'G17_LIVE_APK_SOURCE_COMMIT=' "$L"
! grep -Fq 'gate17_runtime_execution.sh' "$L"
! grep -Fq 'ALFA_G17_PROOT_EXEC' "$L"
! grep -Fq 'ALFA_G17_ROOTFS' "$L"
! grep -Fq 'G17_LIVE_PROOT=' "$L"
! grep -Fq 'G17_LIVE_ROOTFS=' "$L"
echo G17_ANDROID_INSTRUMENTATION_BOUNDARY=PASS
echo G17_LIVE_DELEGATES_TO_ANDROID=PASS
echo G17_APK_PROVENANCE_BOUNDARY=PASS
echo G17_INSTRUMENTATION_NAMESPACE_BOUNDARY=PASS